// ─────────────────────────────────────────────────────────────
// Pearloom / app/(shell)/templates/page.tsx
//
// Templates browser — "Start from a story that feels like yours."
// Every tile is a real themed site vignette generated by the
// production theme engine (same CSS pipeline that paints
// published sites). See TemplatesBrowser.tsx / TemplateVignette.tsx.
//
// Previously this route redirected to /store. The Theme Store is
// for swapping the look of an existing site; this surface is for
// hosts who haven't started yet and want to choose a story
// shape before they build. Both surfaces share the underlying
// PACKS data so a template chosen here paints the same look
// the host could have bought in the store.
// ─────────────────────────────────────────────────────────────

import type { Metadata } from 'next';
import { TemplatesBrowser } from './TemplatesBrowser';

export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: 'Templates · Pearloom',
  description:
    'Start from a story that feels like yours. Browse 15 lovingly designed templates — weddings, milestones, gatherings, memorials, trips, and soft launches. Each one is a full site, ready to fill with your people, photos, and moments.',
};

export default function TemplatesPage() {
  return <TemplatesBrowser />;
}
