// ─────────────────────────────────────────────────────────────
// Pearloom / lib/font-catalog.ts
// Comprehensive curated Google Fonts pairings for weddings.
// 50+ entries across 7 aesthetic categories.
// ─────────────────────────────────────────────────────────────

export interface FontPair {
  id: string;
  heading: string;       // Google Font name for headings
  body: string;          // Google Font name for body text
  category: 'romantic' | 'modern' | 'classic' | 'playful' | 'editorial' | 'rustic' | 'luxe';
  mood: string;          // e.g. "Dreamy & Soft"
  preview: string;       // A sample wedding phrase for preview
  headingWeight: number; // e.g. 400, 500, 700
  bodyWeight: number;    // e.g. 400
  headingStyle?: 'italic' | 'normal';
  pairRationale: string; // Why these two fonts work together
}

export const FONT_CATALOG: FontPair[] = [

  // ── Romantic ────────────────────────────────────────────────
  {
    id: 'cormorant-jost',
    heading: 'Cormorant Garamond',
    body: 'Jost',
    category: 'romantic',
    mood: 'Dreamy & Soft',
    preview: 'Forever Begins Today',
    headingWeight: 300,
    bodyWeight: 400,
    headingStyle: 'italic',
    pairRationale: 'Cormorant\'s delicate italic serifs evoke old-world romance while Jost\'s geometric clarity keeps it readable and contemporary.',
  },
  {
    id: 'playfair-raleway',
    heading: 'Playfair Display',
    body: 'Raleway',
    category: 'romantic',
    mood: 'Timeless Elegance',
    preview: 'Two Hearts, One Story',
    headingWeight: 700,
    bodyWeight: 400,
    headingStyle: 'italic',
    pairRationale: 'Playfair\'s high-contrast serifs bring editorial drama; Raleway\'s thin letterforms balance with refined air.',
  },
  {
    id: 'great-vibes-montserrat',
    heading: 'Great Vibes',
    body: 'Montserrat',
    category: 'romantic',
    mood: 'Flowing & Whimsical',
    preview: 'Emma & James',
    headingWeight: 400,
    bodyWeight: 400,
    pairRationale: 'Great Vibes\'s calligraphic flourish creates emotional impact in heroes; Montserrat grounds body copy with geometric stability.',
  },
  {
    id: 'libre-baskerville-lato',
    heading: 'Libre Baskerville',
    body: 'Lato',
    category: 'romantic',
    mood: 'Warm & Trustworthy',
    preview: 'A Love Worth Celebrating',
    headingWeight: 700,
    bodyWeight: 400,
    pairRationale: 'Baskerville brings warmth and heritage; Lato\'s humanist curves echo those qualities without competing.',
  },
  {
    id: 'eb-garamond-source-sans',
    heading: 'EB Garamond',
    body: 'Source Sans 3',
    category: 'romantic',
    mood: 'Literary & Intimate',
    preview: 'Written in the Stars',
    headingWeight: 500,
    bodyWeight: 400,
    headingStyle: 'italic',
    pairRationale: 'EB Garamond\'s Renaissance letterforms feel handcrafted and poetic; Source Sans 3 provides clean, modern contrast.',
  },
  {
    id: 'mrs-saint-delafield-josefin',
    heading: 'Mrs Saint Delafield',
    body: 'Josefin Sans',
    category: 'romantic',
    mood: 'Script & Geometry',
    preview: 'Save the Date',
    headingWeight: 400,
    bodyWeight: 300,
    pairRationale: 'The ornate script heading finds perfect tension with Josefin\'s rigid geometric lowercase, a classic high-fashion pairing.',
  },
  {
    id: 'tangerine-open-sans',
    heading: 'Tangerine',
    body: 'Open Sans',
    category: 'romantic',
    mood: 'Airy & Romantic',
    preview: 'With All My Love',
    headingWeight: 700,
    bodyWeight: 400,
    pairRationale: 'Tangerine\'s flowing calligraphy needs a reliable workhorse beside it; Open Sans is universally legible and unobtrusive.',
  },
  {
    id: 'cinzel-decorative-cinzel',
    heading: 'Cinzel Decorative',
    body: 'Cinzel',
    category: 'romantic',
    mood: 'Grand & Ceremonial',
    preview: 'The Grand Affair',
    headingWeight: 400,
    bodyWeight: 400,
    pairRationale: 'A refined same-family pairing: decorative titling meets clean classical roman in body for coherent ceremony program feel.',
  },
  {
    id: 'alex-brush-nunito',
    heading: 'Alex Brush',
    body: 'Nunito',
    category: 'romantic',
    mood: 'Soft & Gentle',
    preview: 'I Do, Always',
    headingWeight: 400,
    bodyWeight: 400,
    pairRationale: 'Alex Brush\'s flowing script stays legible at display sizes; Nunito\'s rounded terminals carry the soft romantic mood into body text.',
  },

  // ── Modern ──────────────────────────────────────────────────
  {
    id: 'dm-serif-dm-sans',
    heading: 'DM Serif Display',
    body: 'DM Sans',
    category: 'modern',
    mood: 'Clean & Contemporary',
    preview: 'A New Chapter',
    headingWeight: 400,
    bodyWeight: 400,
    pairRationale: 'A purpose-built superfamily: the serif display and sans body share identical proportions, giving effortless typographic harmony.',
  },
  {
    id: 'bodoni-moda-inter',
    heading: 'Bodoni Moda',
    body: 'Inter',
    category: 'modern',
    mood: 'Bold & High-Fashion',
    preview: 'Modern Love',
    headingWeight: 400,
    bodyWeight: 400,
    headingStyle: 'italic',
    pairRationale: 'Bodoni Moda\'s extreme stroke contrast brings couture energy; Inter\'s neutral precision keeps content supremely readable.',
  },
  {
    id: 'bebas-neue-roboto',
    heading: 'Bebas Neue',
    body: 'Roboto',
    category: 'modern',
    mood: 'Architectural & Strong',
    preview: 'LOVE IN CAPITAL LETTERS',
    headingWeight: 400,
    bodyWeight: 400,
    pairRationale: 'Bebas Neue\'s condensed capitals create strong graphic impact; Roboto is the trusted body companion for legibility at any size.',
  },
  {
    id: 'fraunces-figtree',
    heading: 'Fraunces',
    body: 'Figtree',
    category: 'modern',
    mood: 'Warm Modernism',
    preview: 'The Story of Us',
    headingWeight: 300,
    bodyWeight: 400,
    headingStyle: 'italic',
    pairRationale: 'Fraunces is a variable "wonky" serif full of personality; Figtree\'s geometric sans echoes its humanist warmth without competing.',
  },
  {
    id: 'syne-nunito-sans',
    heading: 'Syne',
    body: 'Nunito Sans',
    category: 'modern',
    mood: 'Graphic & Expressive',
    preview: 'Our Celebration',
    headingWeight: 700,
    bodyWeight: 400,
    pairRationale: 'Syne\'s distinctive display alternation creates instant recognition; Nunito Sans\'s open apertures make body copy welcoming.',
  },
  {
    id: 'outfit-plus-jakarta',
    heading: 'Outfit',
    body: 'Plus Jakarta Sans',
    category: 'modern',
    mood: 'Crisp & Minimal',
    preview: 'Together Is a Beautiful Place',
    headingWeight: 600,
    bodyWeight: 400,
    pairRationale: 'Both fonts share low-contrast geometric DNA; Outfit\'s wide tracking in headings pairs naturally with Plus Jakarta Sans\'s compact efficiency.',
  },
  {
    id: 'cabinet-grotesk-manrope',
    heading: 'Protest Guerrilla',
    body: 'Manrope',
    category: 'modern',
    mood: 'Bold & Unexpected',
    preview: 'Say Yes',
    headingWeight: 400,
    bodyWeight: 400,
    pairRationale: 'A daring display choice for the rule-breakers; Manrope\'s refined geometric forms ensure body text remains professional.',
  },
  {
    id: 'tenor-sans-source-sans3',
    heading: 'Tenor Sans',
    body: 'Source Sans 3',
    category: 'modern',
    mood: 'Architectural Calm',
    preview: 'Designed for Forever',
    headingWeight: 400,
    bodyWeight: 400,
    pairRationale: 'Tenor Sans has an elegant, slightly Art Deco neutrality that feels architectural; Source Sans 3 is the cleanest body workhorse available.',
  },
  {
    id: 'recoleta-inter',
    heading: 'Recoleta',
    body: 'Inter',
    category: 'modern',
    mood: 'Retro-Modern',
    preview: 'Love Stories Since Then',
    headingWeight: 400,
    bodyWeight: 400,
    pairRationale: 'Recoleta\'s 70s slab-serif curves bring warmth and retro charm; Inter anchors it with contemporary digital precision.',
  },

  // ── Classic ─────────────────────────────────────────────────
  {
    id: 'crimson-merriweather',
    heading: 'Crimson Text',
    body: 'Merriweather',
    category: 'classic',
    mood: 'Bookish & Timeless',
    preview: 'A Chapter Worth Reading',
    headingWeight: 600,
    bodyWeight: 400,
    headingStyle: 'italic',
    pairRationale: 'Two classical serifs from different eras; Crimson Text\'s editorial italic contrasts with Merriweather\'s sturdy screen-optimized body.',
  },
  {
    id: 'libre-baskerville-eb-garamond',
    heading: 'Libre Baskerville',
    body: 'EB Garamond',
    category: 'classic',
    mood: 'Heritage & Warmth',
    preview: 'In This Moment, Forever',
    headingWeight: 700,
    bodyWeight: 400,
    pairRationale: 'Two classical British serifs that share sturdy stroke weight while differing enough in personality to create readable hierarchy.',
  },
  {
    id: 'cardo-cabin',
    heading: 'Cardo',
    body: 'Cabin',
    category: 'classic',
    mood: 'Scholarly & Grounded',
    preview: 'With This Ring',
    headingWeight: 700,
    bodyWeight: 400,
    pairRationale: 'Cardo\'s classical revival serif brings Old World gravitas; Cabin\'s humanist sans makes the body copy modern and approachable.',
  },
  {
    id: 'spectral-karla',
    heading: 'Spectral',
    body: 'Karla',
    category: 'classic',
    mood: 'Literary & Refined',
    preview: 'The Words We Choose',
    headingWeight: 300,
    bodyWeight: 400,
    headingStyle: 'italic',
    pairRationale: 'Spectral\'s ink-trap serif is designed for screens but feels print-classical; Karla\'s quirky grotesque provides a contemporary edge.',
  },
  {
    id: 'lora-open-sans',
    heading: 'Lora',
    body: 'Open Sans',
    category: 'classic',
    mood: 'Warm & Dependable',
    preview: 'Our Promise to Each Other',
    headingWeight: 700,
    bodyWeight: 400,
    headingStyle: 'italic',
    pairRationale: 'Lora\'s calligraphic brushwork in serifs adds warmth to headings; Open Sans is the single most-read font on the internet for good reason.',
  },
  {
    id: 'rokkitt-source-sans3',
    heading: 'Rokkitt',
    body: 'Source Sans 3',
    category: 'classic',
    mood: 'Vintage Warmth',
    preview: 'Come Celebrate With Us',
    headingWeight: 700,
    bodyWeight: 400,
    pairRationale: 'Rokkitt\'s slab serif brings vintage poster energy; Source Sans 3\'s clean neutrality prevents the combination from feeling dated.',
  },
  {
    id: 'gfs-didot-lato',
    heading: 'GFS Didot',
    body: 'Lato',
    category: 'classic',
    mood: 'Neo-Classical',
    preview: 'Timeless and True',
    headingWeight: 400,
    bodyWeight: 400,
    pairRationale: 'GFS Didot\'s extreme-contrast didone serif reads as luxuriously classical; Lato\'s humanist warmth tempers that austerity.',
  },
  {
    id: 'playfair-lato',
    heading: 'Playfair Display',
    body: 'Lato',
    category: 'classic',
    mood: 'Stately Romance',
    preview: 'From This Day Forward',
    headingWeight: 700,
    bodyWeight: 400,
    pairRationale: 'Playfair Display\'s high-contrast elegance anchors headings; Lato\'s warm humanist sans makes long reads comfortable.',
  },
  {
    id: 'old-standard-tt-merriweather',
    heading: 'Old Standard TT',
    body: 'Merriweather',
    category: 'classic',
    mood: 'Antiquarian',
    preview: 'Written in History',
    headingWeight: 700,
    bodyWeight: 400,
    headingStyle: 'italic',
    pairRationale: 'Old Standard TT mimics 19th-century book typography; Merriweather\'s screen-hinted body keeps it comfortable to read digitally.',
  },

  // ── Playful ─────────────────────────────────────────────────
  {
    id: 'pacifico-quicksand',
    heading: 'Pacifico',
    body: 'Quicksand',
    category: 'playful',
    mood: 'Carefree & Joyful',
    preview: 'Let\'s Party!',
    headingWeight: 400,
    bodyWeight: 400,
    pairRationale: 'Pacifico\'s retro surf-script is pure fun; Quicksand\'s rounded terminals echo that friendliness without the calligraphic bustle.',
  },
  {
    id: 'dancing-script-nunito',
    heading: 'Dancing Script',
    body: 'Nunito',
    category: 'playful',
    mood: 'Bubbly & Sweet',
    preview: 'We\'re Getting Married!',
    headingWeight: 700,
    bodyWeight: 400,
    pairRationale: 'Dancing Script\'s lively bounce brings energy; Nunito\'s rounded sans carries that softness into body copy seamlessly.',
  },
  {
    id: 'sacramento-raleway',
    heading: 'Sacramento',
    body: 'Raleway',
    category: 'playful',
    mood: 'Flowing & Fun',
    preview: 'Joy, Love & Celebration',
    headingWeight: 400,
    bodyWeight: 400,
    pairRationale: 'Sacramento is a graceful monolinear script that stays legible; Raleway\'s elegant thin letterforms keep the playfulness from becoming silly.',
  },
  {
    id: 'kaushan-script-poppins',
    heading: 'Kaushan Script',
    body: 'Poppins',
    category: 'playful',
    mood: 'Cheerful & Vibrant',
    preview: 'Celebrate Good Times',
    headingWeight: 400,
    bodyWeight: 400,
    pairRationale: 'Kaushan Script\'s expressive brush lettering gives instant personality; Poppins brings pop-art geometric fun to body copy.',
  },
  {
    id: 'lobster-two-cabin',
    heading: 'Lobster Two',
    body: 'Cabin',
    category: 'playful',
    mood: 'Vintage Fun',
    preview: 'Here Comes the Fun',
    headingWeight: 700,
    bodyWeight: 400,
    headingStyle: 'italic',
    pairRationale: 'Lobster Two\'s exuberant retro script creates instant memorability; Cabin\'s geometric humanist sans provides a clean counterweight.',
  },
  {
    id: 'satisfy-open-sans',
    heading: 'Satisfy',
    body: 'Open Sans',
    category: 'playful',
    mood: 'Charming & Warm',
    preview: 'Love is in the Air',
    headingWeight: 400,
    bodyWeight: 400,
    pairRationale: 'Satisfy\'s elegant handwriting style bridges script and playful perfectly; Open Sans makes surrounding text invisible in the best way.',
  },
  {
    id: 'courgette-mulish',
    heading: 'Courgette',
    body: 'Mulish',
    category: 'playful',
    mood: 'Fresh & Lively',
    preview: 'A Day Full of Joy',
    headingWeight: 400,
    bodyWeight: 400,
    pairRationale: 'Courgette\'s italic script feels hand-lettered and spontaneous; Mulish\'s neutral grotesque keeps practical information crystal clear.',
  },
  {
    id: 'parisienne-josefin-sans',
    heading: 'Parisienne',
    body: 'Josefin Sans',
    category: 'playful',
    mood: 'Parisian Chic',
    preview: 'Oui, Pour Toujours',
    headingWeight: 400,
    bodyWeight: 300,
    pairRationale: 'Parisienne\'s haute-couture script feels Parisian and effortlessly chic; Josefin Sans\'s geometric uppercase provides sharp modern contrast.',
  },
  {
    id: 'amatic-sc-raleway',
    heading: 'Amatic SC',
    body: 'Raleway',
    category: 'playful',
    mood: 'Hand-Drawn & Artsy',
    preview: 'Hand-Picked Just for You',
    headingWeight: 700,
    bodyWeight: 400,
    pairRationale: 'Amatic SC\'s hand-drawn quality gives a DIY artisan feel; Raleway\'s refinement elevates the combination beyond craft-fair.',
  },

  // ── Editorial ───────────────────────────────────────────────
  {
    id: 'josefin-sans-josefin-slab',
    heading: 'Josefin Sans',
    body: 'Josefin Slab',
    category: 'editorial',
    mood: 'Geometric Precision',
    preview: 'The Minimal Wedding',
    headingWeight: 700,
    bodyWeight: 400,
    pairRationale: 'A conceptual same-family pairing where both fonts share geometric DNA; the subtle serif-vs-sans tension creates editorial sophistication.',
  },
  {
    id: 'unbounded-outfit',
    heading: 'Unbounded',
    body: 'Outfit',
    category: 'editorial',
    mood: 'Futuristic & Bold',
    preview: 'THE WEDDING',
    headingWeight: 700,
    bodyWeight: 400,
    pairRationale: 'Unbounded\'s wide display proportions feel like editorial magazine spreads; Outfit is the clean companion that prevents overload.',
  },
  {
    id: 'space-grotesk-space-mono',
    heading: 'Space Grotesk',
    body: 'Space Mono',
    category: 'editorial',
    mood: 'Tech & Cosmic',
    preview: 'LAUNCH DATE: OUR FOREVER',
    headingWeight: 700,
    bodyWeight: 400,
    pairRationale: 'Space Grotesk and Space Mono form a conceptual superfamily; the monospaced body adds a playful code-aesthetic unexpected in weddings.',
  },
  {
    id: 'epilogue-work-sans',
    heading: 'Epilogue',
    body: 'Work Sans',
    category: 'editorial',
    mood: 'Clean & Confident',
    preview: 'A New Chapter Begins',
    headingWeight: 800,
    bodyWeight: 400,
    pairRationale: 'Epilogue is built for headlines with optical weight at large sizes; Work Sans is the most refined geometric sans for body copy.',
  },
  {
    id: 'dm-serif-outfit',
    heading: 'DM Serif Display',
    body: 'Outfit',
    category: 'editorial',
    mood: 'Warm Editorial',
    preview: 'A Love Story, Told Well',
    headingWeight: 400,
    bodyWeight: 400,
    headingStyle: 'italic',
    pairRationale: 'DM Serif Display\'s warm ink trap serifs contrast beautifully with Outfit\'s clean geometric lines in a contemporary editorial fashion.',
  },
  {
    id: 'instrument-serif-instrument-sans',
    heading: 'Instrument Serif',
    body: 'Instrument Sans',
    category: 'editorial',
    mood: 'Refined Versatility',
    preview: 'Crafted with Intention',
    headingWeight: 400,
    bodyWeight: 400,
    headingStyle: 'italic',
    pairRationale: 'Google\'s newest superfamily; the serif and sans share near-identical metrics making this pairing technically perfect.',
  },
  {
    id: 'eb-garamond-outfit',
    heading: 'EB Garamond',
    body: 'Outfit',
    category: 'editorial',
    mood: 'Classic Meets Future',
    preview: 'Old Souls, New Beginning',
    headingWeight: 600,
    bodyWeight: 400,
    headingStyle: 'italic',
    pairRationale: 'The extreme historical distance between Garamond (1530s) and Outfit (2021) creates deliberate anachronistic editorial tension.',
  },
  {
    id: 'anybody-dm-sans',
    heading: 'Anybody',
    body: 'DM Sans',
    category: 'editorial',
    mood: 'Variable & Dynamic',
    preview: 'LOVE IN ALL CAPS',
    headingWeight: 900,
    bodyWeight: 400,
    pairRationale: 'Anybody\'s variable width axes allow dramatic display styling; DM Sans brings calm, reliable body text to match any width setting.',
  },
  {
    id: 'syne-dm-sans',
    heading: 'Syne',
    body: 'DM Sans',
    category: 'editorial',
    mood: 'Design-Forward',
    preview: 'Vision Realized',
    headingWeight: 800,
    bodyWeight: 400,
    pairRationale: 'Syne was designed for editorial design publications; DM Sans is the ideal companion for its slightly eccentric proportions.',
  },

  // ── Rustic ──────────────────────────────────────────────────
  {
    id: 'abril-fatface-lora',
    heading: 'Abril Fatface',
    body: 'Lora',
    category: 'rustic',
    mood: 'Bold & Earthy',
    preview: 'Down-Home Love',
    headingWeight: 400,
    bodyWeight: 400,
    pairRationale: 'Abril Fatface\'s ultra-bold display roman brings the energy of vintage broadsheets; Lora\'s gentle brush serif keeps body text warm.',
  },
  {
    id: 'rozha-one-poppins',
    heading: 'Rozha One',
    body: 'Poppins',
    category: 'rustic',
    mood: 'Rustic Charm',
    preview: 'Under the Open Sky',
    headingWeight: 400,
    bodyWeight: 400,
    pairRationale: 'Rozha One\'s high-contrast bold roman has a handcrafted quality; Poppins\'s geometric friendliness keeps the pairing approachable.',
  },
  {
    id: 'zilla-slab-mulish',
    heading: 'Zilla Slab',
    body: 'Mulish',
    category: 'rustic',
    mood: 'Sturdy & Sincere',
    preview: 'Built to Last',
    headingWeight: 700,
    bodyWeight: 400,
    pairRationale: 'Zilla Slab\'s chunky proportions feel like hand-carved wood signage; Mulish\'s clean lines provide reliable contrast.',
  },
  {
    id: 'ultra-karla',
    heading: 'Ultra',
    body: 'Karla',
    category: 'rustic',
    mood: 'Heavy & Heartfelt',
    preview: 'BIG LOVE',
    headingWeight: 400,
    bodyWeight: 400,
    pairRationale: 'Ultra\'s extreme weight creates a striking woodblock print aesthetic; Karla\'s italic grotesque adds character to body copy.',
  },
  {
    id: 'patua-one-cabin',
    heading: 'Patua One',
    body: 'Cabin',
    category: 'rustic',
    mood: 'Country & Warm',
    preview: 'Meet Me in the Field',
    headingWeight: 400,
    bodyWeight: 400,
    pairRationale: 'Patua One evokes hand-stamped letterpress invitation cards; Cabin\'s humanist proportions complement without overwhelming.',
  },
  {
    id: 'philosopher-rubik',
    heading: 'Philosopher',
    body: 'Rubik',
    category: 'rustic',
    mood: 'Thoughtful & Grounded',
    preview: 'Rooted in Love',
    headingWeight: 700,
    bodyWeight: 400,
    headingStyle: 'italic',
    pairRationale: 'Philosopher\'s classical italic draws on Renaissance humanist letterforms; Rubik\'s slightly rounded rectangularity feels like carved stone.',
  },
  {
    id: 'aleo-lato',
    heading: 'Aleo',
    body: 'Lato',
    category: 'rustic',
    mood: 'Organic & Comfortable',
    preview: 'Love Grows Here',
    headingWeight: 700,
    bodyWeight: 400,
    pairRationale: 'Aleo\'s rounded slab serifs feel simultaneously organic and structured; Lato\'s humanist forms share that dual quality at body size.',
  },
  {
    id: 'quando-nunito',
    heading: 'Quando',
    body: 'Nunito',
    category: 'rustic',
    mood: 'Gentle & Natural',
    preview: 'Simple Moments, Big Love',
    headingWeight: 400,
    bodyWeight: 400,
    pairRationale: 'Quando\'s transitional slab has soft, natural proportions; Nunito\'s round terminals mirror that approachable quality throughout.',
  },

  // ── Luxe ────────────────────────────────────────────────────
  {
    id: 'cormorant-cormorant-infant',
    heading: 'Cormorant',
    body: 'Cormorant Infant',
    category: 'luxe',
    mood: 'Pure Luxury',
    preview: 'The Black-Tie Affair',
    headingWeight: 300,
    bodyWeight: 400,
    headingStyle: 'italic',
    pairRationale: 'A refined intra-family pairing from the same designer; the display optical size versus text optical size creates effortless typographic luxury.',
  },
  {
    id: 'marcellus-sc-marcellus',
    heading: 'Marcellus SC',
    body: 'Marcellus',
    category: 'luxe',
    mood: 'Understated Prestige',
    preview: 'AN AFFAIR TO REMEMBER',
    headingWeight: 400,
    bodyWeight: 400,
    pairRationale: 'Marcellus SC\'s small caps evoke engraved stationery; the regular Marcellus body maintains the same serene classical personality.',
  },
  {
    id: 'didact-gothic-philosopher',
    heading: 'Didact Gothic',
    body: 'Philosopher',
    category: 'luxe',
    mood: 'Cool & Intellectual',
    preview: 'A Considered Celebration',
    headingWeight: 400,
    bodyWeight: 400,
    pairRationale: 'Didact Gothic\'s pure geometric rationality is architect-approved; Philosopher\'s classical serif body brings warmth into the precision.',
  },
  {
    id: 'poiret-one-montserrat',
    heading: 'Poiret One',
    body: 'Montserrat',
    category: 'luxe',
    mood: 'Art Deco Glamour',
    preview: 'THE ROARING TWENTIES',
    headingWeight: 400,
    bodyWeight: 300,
    pairRationale: 'Poiret One\'s elegant Art Deco skeleton is one of a kind; Montserrat\'s geometric roots share the same 1920s design DNA.',
  },
  {
    id: 'bodoni-moda-cormorant',
    heading: 'Bodoni Moda',
    body: 'Cormorant Garamond',
    category: 'luxe',
    mood: 'Editorial Luxury',
    preview: 'Vogue Weddings',
    headingWeight: 400,
    bodyWeight: 400,
    headingStyle: 'italic',
    pairRationale: 'Two high-contrast serifs from different centuries; Bodoni Moda\'s fashion-forward neoclassicism meets Cormorant Garamond\'s timeless romance.',
  },
  {
    id: 'cardo-josefin-sans-luxe',
    heading: 'Cardo',
    body: 'Josefin Sans',
    category: 'luxe',
    mood: 'Gallery & Curated',
    preview: 'Curated for You',
    headingWeight: 700,
    bodyWeight: 300,
    headingStyle: 'italic',
    pairRationale: 'Cardo\'s scholarly elegance anchors headings like an art gallery label; Josefin Sans\'s thin geometric tracking signals exclusive curation.',
  },
  {
    id: 'julius-sans-one-raleway',
    heading: 'Julius Sans One',
    body: 'Raleway',
    category: 'luxe',
    mood: 'Spaced & Minimal',
    preview: 'FOREVER   AND   ALWAYS',
    headingWeight: 400,
    bodyWeight: 300,
    pairRationale: 'Julius Sans One\'s wide letter-spacing suggests luxury brand identity; Raleway in light weight continues that premium airy feeling.',
  },
  {
    id: 'cormorant-upright-montserrat',
    heading: 'Cormorant Upright',
    body: 'Montserrat',
    category: 'luxe',
    mood: 'Haute Couture',
    preview: 'Dressed to the Nines',
    headingWeight: 300,
    bodyWeight: 300,
    pairRationale: 'Cormorant Upright\'s extreme hairline serifs achieve extreme elegance; Montserrat in light weight extends that luxury to body text.',
  },
];

// ── Helper: get pairs by category ───────────────────────────
export function getPairsByCategory(
  category: FontPair['category'],
): FontPair[] {
  return FONT_CATALOG.filter((p) => p.category === category);
}

// ── Helper: get pair by id ───────────────────────────────────
export function getPairById(id: string): FontPair | undefined {
  return FONT_CATALOG.find((p) => p.id === id);
}

// ── Helper: all category values ─────────────────────────────
export const FONT_CATEGORIES: FontPair['category'][] = [
  'romantic',
  'modern',
  'classic',
  'playful',
  'editorial',
  'rustic',
  'luxe',
];

// ── Build a Google Fonts URL for a pair ─────────────────────
export function buildFontsUrl(pair: Pick<FontPair, 'heading' | 'body' | 'headingWeight' | 'bodyWeight' | 'headingStyle'>): string {
  const encode = (name: string) => name.replace(/ /g, '+');
  const hStyle = pair.headingStyle === 'italic' ? `ital,wght@1,${pair.headingWeight}` : `wght@${pair.headingWeight}`;
  const bStyle = `wght@${pair.bodyWeight}`;
  return `https://fonts.googleapis.com/css2?family=${encode(pair.heading)}:${hStyle}&family=${encode(pair.body)}:${bStyle}&display=swap`;
}
