'use client';

// ─────────────────────────────────────────────────────────────
// Pearloom / components/editor/ThemeSwitcher.tsx
// One-click preset theme switching with live preview
// ─────────────────────────────────────────────────────────────

import React, { useState } from 'react';
import { motion } from 'framer-motion';
import type { VibeSkin } from '@/lib/vibe-engine';
import { WAVE_PATHS } from '@/lib/vibe-engine';
import type { StoryManifest } from '@/types';

export interface ThemeSwitcherProps {
  currentVibeSkin: VibeSkin;
  manifest: StoryManifest;
  onApply: (newSkin: VibeSkin) => void;
}

// ── Shared section labels default ─────────────────────────────
const DEFAULT_LABELS: VibeSkin['sectionLabels'] = {
  story: 'Our Story',
  events: 'Our Celebration',
  registry: 'Our Registry',
  travel: 'Getting Here',
  faqs: 'Good to Know',
  rsvp: "We'd Love to See You",
  photos: 'Our Photos',
};

// ── 30 Hand-crafted preset themes ─────────────────────────────
const PRESET_THEMES: Array<VibeSkin & { name: string }> = [
  // 1. Ivory Garden
  {
    name: 'Ivory Garden',
    curve: 'petal',
    particle: 'petals',
    accentShape: 'leaf',
    sectionEntrance: 'bloom',
    texture: 'floral',
    decorIcons: ['✿', '❦', '✾', '◦', '•'],
    accentSymbol: '✿',
    particleColor: '#a3b18a',
    sectionLabels: DEFAULT_LABELS,
    dividerQuote: 'Where every petal tells a story.',
    cornerStyle: '40% 40% 2rem 2rem / 3rem 3rem 2rem 2rem',
    tone: 'dreamy',
    headingStyle: 'italic-serif',
    cardStyle: 'elevated',
    sectionGradient: 'linear-gradient(135deg, #f9f6ef 0%, #f0eddf 100%)',
    palette: {
      background: '#F7F3E9',
      foreground: '#2C2A1E',
      accent: '#6B8F55',
      accent2: '#71717A',
      card: '#FDFAF2',
      muted: '#8A8570',
      highlight: '#4E7440',
      subtle: '#F3F0E5',
      ink: '#1A1810',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    wavePath: WAVE_PATHS['petal'].d,
    wavePathInverted: WAVE_PATHS['petal'].di,
    aiGenerated: false,
  },
  // 2. Midnight Luxe
  {
    name: 'Midnight Luxe',
    curve: 'arch',
    particle: 'stars',
    accentShape: 'diamond',
    sectionEntrance: 'fade-up',
    texture: 'starfield',
    decorIcons: ['✦', '◈', '◇', '✧', '⋆'],
    accentSymbol: '◈',
    particleColor: '#d4af37',
    sectionLabels: DEFAULT_LABELS,
    dividerQuote: 'A love written in the stars.',
    cornerStyle: '50% 50% 1.5rem 1.5rem / 3rem 3rem 1.5rem 1.5rem',
    tone: 'luxurious',
    headingStyle: 'thin-elegant',
    cardStyle: 'glass',
    sectionGradient: 'linear-gradient(135deg, #1C1A26 0%, #22202E 100%)',
    palette: {
      background: '#1A1822',
      foreground: '#F5F0E8',
      accent: '#D4AF37',
      accent2: '#8B7240',
      card: '#201E2C',
      muted: '#7A748A',
      highlight: '#F0D060',
      subtle: '#1E1C28',
      ink: '#FDFAF2',
    },
    fonts: { heading: 'Cormorant Garamond', body: 'Raleway' },
    wavePath: WAVE_PATHS['arch'].d,
    wavePathInverted: WAVE_PATHS['arch'].di,
    aiGenerated: false,
  },
  // 3. Coastal Breeze
  {
    name: 'Coastal Breeze',
    curve: 'wave',
    particle: 'bubbles',
    accentShape: 'ring',
    sectionEntrance: 'drift',
    texture: 'bokeh',
    decorIcons: ['○', '◯', '◦', '✦', '•'],
    accentSymbol: '○',
    particleColor: '#b8e0ff',
    sectionLabels: DEFAULT_LABELS,
    dividerQuote: 'Where the sea meets forever.',
    cornerStyle: '1.5rem',
    tone: 'dreamy',
    headingStyle: 'italic-serif',
    cardStyle: 'outlined',
    sectionGradient: 'linear-gradient(135deg, #EBF4FC 0%, #D8EEF9 100%)',
    palette: {
      background: '#EBF4FC',
      foreground: '#1A3040',
      accent: '#C8A96E',
      accent2: '#8DBDD4',
      card: '#F5F9FD',
      muted: '#7A94A4',
      highlight: '#3D7EA8',
      subtle: '#F0F7FB',
      ink: '#0D1E2A',
    },
    fonts: { heading: 'DM Serif Display', body: 'DM Sans' },
    wavePath: WAVE_PATHS['wave'].d,
    wavePathInverted: WAVE_PATHS['wave'].di,
    aiGenerated: false,
  },
  // 4. Forest Romance
  {
    name: 'Forest Romance',
    curve: 'organic',
    particle: 'leaves',
    accentShape: 'leaf',
    sectionEntrance: 'bloom',
    texture: 'linen',
    decorIcons: ['⧱', '◦', '✦', '⦿', '•'],
    accentSymbol: '⧱',
    particleColor: '#a8d5a2',
    sectionLabels: DEFAULT_LABELS,
    dividerQuote: 'Love rooted deep as ancient oaks.',
    cornerStyle: '2rem 4rem 2rem 4rem',
    tone: 'rustic',
    headingStyle: 'italic-serif',
    cardStyle: 'solid',
    sectionGradient: 'linear-gradient(135deg, #1E2B18 0%, #243220 100%)',
    palette: {
      background: '#1E2B18',
      foreground: '#F0EDD8',
      accent: '#C8B87A',
      accent2: '#6B8A5A',
      card: '#243220',
      muted: '#7A8E70',
      highlight: '#E0D090',
      subtle: '#223019',
      ink: '#F5F2E0',
    },
    fonts: { heading: 'Libre Baskerville', body: 'Lato' },
    wavePath: WAVE_PATHS['organic'].d,
    wavePathInverted: WAVE_PATHS['organic'].di,
    aiGenerated: false,
  },
  // 5. Blush Editorial
  {
    name: 'Blush Editorial',
    curve: 'geometric',
    particle: 'sakura',
    accentShape: 'arch',
    sectionEntrance: 'reveal',
    texture: 'paper',
    decorIcons: ['◈', '◇', '✦', '◉', '○'],
    accentSymbol: '◈',
    particleColor: '#f3d1d8',
    sectionLabels: DEFAULT_LABELS,
    dividerQuote: 'Love in the bloom of everything.',
    cornerStyle: '0',
    tone: 'intimate',
    headingStyle: 'bold-editorial',
    cardStyle: 'minimal',
    sectionGradient: 'linear-gradient(135deg, #FBF0F2 0%, #F5E4E8 100%)',
    palette: {
      background: '#FBF0F2',
      foreground: '#2E1018',
      accent: '#7A1E3A',
      accent2: '#D4A0AE',
      card: '#FDF7F8',
      muted: '#9E7880',
      highlight: '#5E1228',
      subtle: '#F8ECF0',
      ink: '#1A0810',
    },
    fonts: { heading: 'Bodoni Moda', body: 'Montserrat' },
    wavePath: WAVE_PATHS['geometric'].d,
    wavePathInverted: WAVE_PATHS['geometric'].di,
    aiGenerated: false,
  },
  // 6. Minimalist Modern
  {
    name: 'Minimalist Modern',
    curve: 'geometric',
    particle: 'petals',
    accentShape: 'ring',
    sectionEntrance: 'fade-up',
    texture: 'none',
    decorIcons: ['·', '—', '·', '—', '·'],
    accentSymbol: '—',
    particleColor: '#000000',
    sectionLabels: DEFAULT_LABELS,
    dividerQuote: 'Less is more. Love is everything.',
    cornerStyle: '0',
    tone: 'intimate',
    headingStyle: 'uppercase-tracked',
    cardStyle: 'minimal',
    sectionGradient: 'linear-gradient(135deg, #FFFFFF 0%, #F8F8F8 100%)',
    palette: {
      background: '#FFFFFF',
      foreground: '#0A0A0A',
      accent: '#0A0A0A',
      accent2: '#555555',
      card: '#F8F8F8',
      muted: '#888888',
      highlight: '#333333',
      subtle: '#F5F5F5',
      ink: '#000000',
    },
    fonts: { heading: 'Space Grotesk', body: 'Inter' },
    wavePath: WAVE_PATHS['geometric'].d,
    wavePathInverted: WAVE_PATHS['geometric'].di,
    aiGenerated: false,
  },
  // 7. Rustic Harvest
  {
    name: 'Rustic Harvest',
    curve: 'organic',
    particle: 'leaves',
    accentShape: 'leaf',
    sectionEntrance: 'drift',
    texture: 'linen',
    decorIcons: ['✿', '✦', '•', '⧱', '◦'],
    accentSymbol: '✦',
    particleColor: '#c5734a',
    sectionLabels: DEFAULT_LABELS,
    dividerQuote: 'Harvest moon, harvest love.',
    cornerStyle: '2rem 4rem 2rem 4rem',
    tone: 'rustic',
    headingStyle: 'bold-editorial',
    cardStyle: 'solid',
    sectionGradient: 'linear-gradient(135deg, #F5EAD8 0%, #EDDCC8 100%)',
    palette: {
      background: '#F0E2C8',
      foreground: '#2C1808',
      accent: '#C0562A',
      accent2: '#E8A87C',
      card: '#F7EDD8',
      muted: '#9E7858',
      highlight: '#8C3A18',
      subtle: '#F5EAD8',
      ink: '#1A0E04',
    },
    fonts: { heading: 'Abril Fatface', body: 'Lora' },
    wavePath: WAVE_PATHS['organic'].d,
    wavePathInverted: WAVE_PATHS['organic'].di,
    aiGenerated: false,
  },
  // 8. Celestial Night
  {
    name: 'Celestial Night',
    curve: 'arch',
    particle: 'stars',
    accentShape: 'infinity',
    sectionEntrance: 'float',
    texture: 'starfield',
    decorIcons: ['✦', '✧', '☽', '⋆', '✩'],
    accentSymbol: '☽',
    particleColor: '#c8d8f0',
    sectionLabels: DEFAULT_LABELS,
    dividerQuote: 'Written in moonlight, sealed with stars.',
    cornerStyle: '50% 50% 1.5rem 1.5rem / 3rem 3rem 1.5rem 1.5rem',
    tone: 'cosmic',
    headingStyle: 'uppercase-tracked',
    cardStyle: 'glass',
    sectionGradient: 'linear-gradient(135deg, #0D1428 0%, #111C38 100%)',
    palette: {
      background: '#0D1428',
      foreground: '#E8EEF8',
      accent: '#9AB0D8',
      accent2: '#5070A8',
      card: '#111C38',
      muted: '#5A6890',
      highlight: '#C0D0F0',
      subtle: '#0F1830',
      ink: '#F0F4FC',
    },
    fonts: { heading: 'Cinzel', body: 'Raleway' },
    wavePath: WAVE_PATHS['arch'].d,
    wavePathInverted: WAVE_PATHS['arch'].di,
    aiGenerated: false,
  },
  // 9. Garden Party
  {
    name: 'Garden Party',
    curve: 'petal',
    particle: 'petals',
    accentShape: 'leaf',
    sectionEntrance: 'bloom',
    texture: 'floral',
    decorIcons: ['✿', '❦', '✾', '⦿', '◦'],
    accentSymbol: '❦',
    particleColor: '#f9c6c9',
    sectionLabels: DEFAULT_LABELS,
    dividerQuote: 'Love is always in bloom.',
    cornerStyle: '40% 40% 2rem 2rem / 3rem 3rem 2rem 2rem',
    tone: 'playful',
    headingStyle: 'script-like',
    cardStyle: 'elevated',
    sectionGradient: 'linear-gradient(135deg, #EEF7EE 0%, #E0F0E0 100%)',
    palette: {
      background: '#EEF7EE',
      foreground: '#1C2C1C',
      accent: '#E0705A',
      accent2: '#A8C8A8',
      card: '#F5FBF5',
      muted: '#7A9A7A',
      highlight: '#C05040',
      subtle: '#EDF6ED',
      ink: '#0E1A0E',
    },
    fonts: { heading: 'Dancing Script', body: 'Nunito' },
    wavePath: WAVE_PATHS['petal'].d,
    wavePathInverted: WAVE_PATHS['petal'].di,
    aiGenerated: false,
  },
  // 10. Golden Hour
  {
    name: 'Golden Hour',
    curve: 'organic',
    particle: 'fireflies',
    accentShape: 'ring',
    sectionEntrance: 'fade-up',
    texture: 'bokeh',
    decorIcons: ['✦', '◇', '•', '✧', '◦'],
    accentSymbol: '✦',
    particleColor: '#ffd966',
    sectionLabels: DEFAULT_LABELS,
    dividerQuote: 'Golden light, golden love.',
    cornerStyle: '2rem 4rem 2rem 4rem',
    tone: 'luxurious',
    headingStyle: 'italic-serif',
    cardStyle: 'elevated',
    sectionGradient: 'linear-gradient(135deg, #FBF0DC 0%, #F5E4C4 100%)',
    palette: {
      background: '#FBF0DC',
      foreground: '#2A1A08',
      accent: '#C87820',
      accent2: '#E8C070',
      card: '#FDF6E8',
      muted: '#9A8060',
      highlight: '#A05C10',
      subtle: '#F8ECD4',
      ink: '#180E04',
    },
    fonts: { heading: 'EB Garamond', body: 'Source Sans 3' },
    wavePath: WAVE_PATHS['organic'].d,
    wavePathInverted: WAVE_PATHS['organic'].di,
    aiGenerated: false,
  },
  // 11. Arctic Winter
  {
    name: 'Arctic Winter',
    curve: 'geometric',
    particle: 'snowflakes',
    accentShape: 'diamond',
    sectionEntrance: 'float',
    texture: 'none',
    decorIcons: ['❄', '✻', '✼', '✦', '◦'],
    accentSymbol: '❄',
    particleColor: '#a8c8e8',
    sectionLabels: DEFAULT_LABELS,
    dividerQuote: 'Pure as the first snowfall.',
    cornerStyle: '0',
    tone: 'dreamy',
    headingStyle: 'thin-elegant',
    cardStyle: 'outlined',
    sectionGradient: 'linear-gradient(135deg, #F0F6FC 0%, #E4EEF8 100%)',
    palette: {
      background: '#F0F6FC',
      foreground: '#1A2840',
      accent: '#4878A8',
      accent2: '#90B4D0',
      card: '#F8FBFE',
      muted: '#7090A8',
      highlight: '#2A5888',
      subtle: '#EAF2F8',
      ink: '#0E1820',
    },
    fonts: { heading: 'Syne', body: 'Nunito Sans' },
    wavePath: WAVE_PATHS['geometric'].d,
    wavePathInverted: WAVE_PATHS['geometric'].di,
    aiGenerated: false,
  },
  // 12. Tropical Bloom
  {
    name: 'Tropical Bloom',
    curve: 'wave',
    particle: 'confetti',
    accentShape: 'arch',
    sectionEntrance: 'bloom',
    texture: 'bokeh',
    decorIcons: ['✿', '◦', '✦', '❦', '•'],
    accentSymbol: '✿',
    particleColor: '#c3f5a9',
    sectionLabels: DEFAULT_LABELS,
    dividerQuote: 'Love bright as a tropical sunrise.',
    cornerStyle: '1.5rem',
    tone: 'playful',
    headingStyle: 'script-like',
    cardStyle: 'elevated',
    sectionGradient: 'linear-gradient(135deg, #FBF7F0 0%, #F5EEE4 100%)',
    palette: {
      background: '#FBF7F0',
      foreground: '#1C2010',
      accent: '#E05830',
      accent2: '#48A060',
      card: '#FDF9F4',
      muted: '#8A9070',
      highlight: '#C04020',
      subtle: '#F8F4EC',
      ink: '#0E1008',
    },
    fonts: { heading: 'Pacifico', body: 'Quicksand' },
    wavePath: WAVE_PATHS['wave'].d,
    wavePathInverted: WAVE_PATHS['wave'].di,
    aiGenerated: false,
  },
  // 13. Art Deco Glamour
  {
    name: 'Art Deco Glamour',
    curve: 'geometric',
    particle: 'stars',
    accentShape: 'diamond',
    sectionEntrance: 'reveal',
    texture: 'none',
    decorIcons: ['◆', '◇', '✧', '❖', '▣'],
    accentSymbol: '◆',
    particleColor: '#c9a84c',
    sectionLabels: {
      story: 'The Grand Affair',
      events: 'The Soirée',
      registry: 'The Wish List',
      travel: 'Your Arrival',
      faqs: 'Need to Know',
      rsvp: 'Reply in Style',
      photos: 'The Gallery',
    },
    dividerQuote: 'Glamour is a state of the heart.',
    cornerStyle: '0',
    tone: 'luxurious',
    headingStyle: 'uppercase-tracked',
    cardStyle: 'glass',
    sectionGradient: 'linear-gradient(135deg, #0D0D0D 0%, #1A1610 100%)',
    palette: {
      background: '#0D0D0D',
      foreground: '#F0E8D4',
      accent: '#C9A84C',
      accent2: '#8A7434',
      card: '#141210',
      muted: '#8A8070',
      highlight: '#E8C860',
      subtle: '#121010',
      ink: '#F5EFE0',
    },
    fonts: { heading: 'Cinzel', body: 'Raleway' },
    wavePath: WAVE_PATHS['geometric'].d,
    wavePathInverted: WAVE_PATHS['geometric'].di,
    aiGenerated: false,
  },
  // 14. Tuscan Villa
  {
    name: 'Tuscan Villa',
    curve: 'organic',
    particle: 'fireflies',
    accentShape: 'leaf',
    sectionEntrance: 'drift',
    texture: 'linen',
    decorIcons: ['✦', '◎', '❀', '☀', '✿'],
    accentSymbol: '✦',
    particleColor: '#c8844a',
    sectionLabels: {
      story: 'La Nostra Storia',
      events: 'La Festa',
      registry: 'I Nostri Desideri',
      travel: 'Come Arrivare',
      faqs: 'Buono a Sapersi',
      rsvp: 'Conferma la Presenza',
      photos: 'I Nostri Ricordi',
    },
    dividerQuote: 'Under the Tuscan sun, love finds its way.',
    cornerStyle: '2rem 4rem 2rem 4rem',
    tone: 'intimate',
    headingStyle: 'italic-serif',
    cardStyle: 'elevated',
    sectionGradient: 'linear-gradient(135deg, #F5EDE0 0%, #EDE0CC 100%)',
    palette: {
      background: '#F5EDE0',
      foreground: '#2A1F14',
      accent: '#B8693D',
      accent2: '#D4A070',
      card: '#FAF4EA',
      muted: '#8A7460',
      highlight: '#965028',
      subtle: '#F0E8DA',
      ink: '#1A1008',
    },
    fonts: { heading: 'Cormorant Garamond', body: 'Lora' },
    wavePath: WAVE_PATHS['organic'].d,
    wavePathInverted: WAVE_PATHS['organic'].di,
    aiGenerated: false,
  },
  // 15. French Chateau
  {
    name: 'French Chateau',
    curve: 'arch',
    particle: 'petals',
    accentShape: 'arch',
    sectionEntrance: 'bloom',
    texture: 'paper',
    decorIcons: ['❋', '✧', '◆', '✿', '✦'],
    accentSymbol: '❋',
    particleColor: '#8aabcc',
    sectionLabels: {
      story: 'Notre Histoire',
      events: 'La Célébration',
      registry: 'Liste de Souhaits',
      travel: 'Comment Venir',
      faqs: 'Bon à Savoir',
      rsvp: 'Répondez S\'il Vous Plaît',
      photos: 'Nos Photos',
    },
    dividerQuote: 'L\'amour est un jardin secret.',
    cornerStyle: '50% 50% 1.5rem 1.5rem / 3rem 3rem 1.5rem 1.5rem',
    tone: 'dreamy',
    headingStyle: 'italic-serif',
    cardStyle: 'elevated',
    sectionGradient: 'linear-gradient(135deg, #F8F4EE 0%, #EDE8E0 100%)',
    palette: {
      background: '#F8F4EE',
      foreground: '#1A2744',
      accent: '#6B8CAE',
      accent2: '#A0B8D0',
      card: '#FDFAF6',
      muted: '#7A8898',
      highlight: '#4A6A8E',
      subtle: '#F4F0EA',
      ink: '#0E1828',
    },
    fonts: { heading: 'Libre Baskerville', body: 'Source Sans 3' },
    wavePath: WAVE_PATHS['arch'].d,
    wavePathInverted: WAVE_PATHS['arch'].di,
    aiGenerated: false,
  },
  // 16. Enchanted Forest
  {
    name: 'Enchanted Forest',
    curve: 'organic',
    particle: 'fireflies',
    accentShape: 'leaf',
    sectionEntrance: 'drift',
    texture: 'none',
    decorIcons: ['🌿', '✦', '❋', '◎', '✧'],
    accentSymbol: '🌿',
    particleColor: '#3ea868',
    sectionLabels: {
      story: 'Into the Woods',
      events: 'The Gathering',
      registry: 'Woodland Wishes',
      travel: 'Find the Path',
      faqs: 'Forest Lore',
      rsvp: 'Answer the Call',
      photos: 'Enchanted Moments',
    },
    dividerQuote: 'Deep in the forest, love glows brightest.',
    cornerStyle: '2rem 4rem 2rem 4rem',
    tone: 'cosmic',
    headingStyle: 'italic-serif',
    cardStyle: 'glass',
    sectionGradient: 'linear-gradient(135deg, #0C1A0F 0%, #142818 100%)',
    palette: {
      background: '#0C1A0F',
      foreground: '#D4E8D0',
      accent: '#2E7D52',
      accent2: '#5AA878',
      card: '#112216',
      muted: '#6A9A70',
      highlight: '#40B070',
      subtle: '#0F1E12',
      ink: '#E8F5E4',
    },
    fonts: { heading: 'EB Garamond', body: 'Nunito' },
    wavePath: WAVE_PATHS['organic'].d,
    wavePathInverted: WAVE_PATHS['organic'].di,
    aiGenerated: false,
  },
  // 17. Desert Boho
  {
    name: 'Desert Boho',
    curve: 'cascade',
    particle: 'leaves',
    accentShape: 'ring',
    sectionEntrance: 'drift',
    texture: 'linen',
    decorIcons: ['✦', '◆', '☀', '▲', '◎'],
    accentSymbol: '☀',
    particleColor: '#d47838',
    sectionLabels: {
      story: 'Our Wandering Tale',
      events: 'The Gathering Under Stars',
      registry: 'Desert Finds',
      travel: 'The Journey',
      faqs: 'Trail Notes',
      rsvp: 'Join the Caravan',
      photos: 'Sun-Kissed Memories',
    },
    dividerQuote: 'Wild hearts find home in the desert wind.',
    cornerStyle: '1.5rem',
    tone: 'wild',
    headingStyle: 'bold-editorial',
    cardStyle: 'solid',
    sectionGradient: 'linear-gradient(135deg, #F5E6D3 0%, #E8D4BC 100%)',
    palette: {
      background: '#F5E6D3',
      foreground: '#2D1E0E',
      accent: '#C4622D',
      accent2: '#E8A060',
      card: '#FAF0E4',
      muted: '#9A7A58',
      highlight: '#A04818',
      subtle: '#F0E0CC',
      ink: '#1A1008',
    },
    fonts: { heading: 'Josefin Sans', body: 'Quicksand' },
    wavePath: WAVE_PATHS['cascade'].d,
    wavePathInverted: WAVE_PATHS['cascade'].di,
    aiGenerated: false,
  },
  // 18. Modern Glam
  {
    name: 'Modern Glam',
    curve: 'geometric',
    particle: 'confetti',
    accentShape: 'diamond',
    sectionEntrance: 'reveal',
    texture: 'none',
    decorIcons: ['◆', '✧', '★', '◇', '▪'],
    accentSymbol: '★',
    particleColor: '#f07ab8',
    sectionLabels: {
      story: 'How It Started',
      events: 'The Main Event',
      registry: 'Gift Edit',
      travel: 'Getting There',
      faqs: 'The Details',
      rsvp: 'Save Your Spot',
      photos: 'Captured Moments',
    },
    dividerQuote: 'Bold love deserves a bold stage.',
    cornerStyle: '0',
    tone: 'luxurious',
    headingStyle: 'uppercase-tracked',
    cardStyle: 'minimal',
    sectionGradient: 'linear-gradient(135deg, #FAFAFA 0%, #F2F0F4 100%)',
    palette: {
      background: '#FAFAFA',
      foreground: '#111111',
      accent: '#E84393',
      accent2: '#F0A0C8',
      card: '#FFFFFF',
      muted: '#888888',
      highlight: '#C0306E',
      subtle: '#F8F6FA',
      ink: '#000000',
    },
    fonts: { heading: 'Outfit', body: 'Inter' },
    wavePath: WAVE_PATHS['geometric'].d,
    wavePathInverted: WAVE_PATHS['geometric'].di,
    aiGenerated: false,
  },
  // 19. Vintage Romance
  {
    name: 'Vintage Romance',
    curve: 'petal',
    particle: 'petals',
    accentShape: 'arch',
    sectionEntrance: 'bloom',
    texture: 'paper',
    decorIcons: ['❀', '✿', '✦', '◎', '❋'],
    accentSymbol: '❀',
    particleColor: '#d4a0a0',
    sectionLabels: {
      story: 'A Love Letter',
      events: 'The Celebration',
      registry: 'Keepsakes & Wishes',
      travel: 'Directions to Us',
      faqs: 'A Few Things to Know',
      rsvp: 'Kindly Respond',
      photos: 'Cherished Moments',
    },
    dividerQuote: 'Some love stories never grow old.',
    cornerStyle: '40% 40% 2rem 2rem / 3rem 3rem 2rem 2rem',
    tone: 'intimate',
    headingStyle: 'italic-serif',
    cardStyle: 'elevated',
    sectionGradient: 'linear-gradient(135deg, #FAF5EE 0%, #F0E8DE 100%)',
    palette: {
      background: '#FAF5EE',
      foreground: '#3D2E22',
      accent: '#C48B8B',
      accent2: '#D8B0B0',
      card: '#FDFAF6',
      muted: '#9A847A',
      highlight: '#A06868',
      subtle: '#F6F0E8',
      ink: '#261A12',
    },
    fonts: { heading: 'Crimson Text', body: 'Lato' },
    wavePath: WAVE_PATHS['petal'].d,
    wavePathInverted: WAVE_PATHS['petal'].di,
    aiGenerated: false,
  },
  // 20. Tropical Paradise
  {
    name: 'Tropical Paradise',
    curve: 'wave',
    particle: 'confetti',
    accentShape: 'ring',
    sectionEntrance: 'bloom',
    texture: 'bokeh',
    decorIcons: ['🌺', '✦', '☀', '◎', '✧'],
    accentSymbol: '🌺',
    particleColor: '#f09080',
    sectionLabels: {
      story: 'Island Love Story',
      events: 'The Beach Bash',
      registry: 'Tropical Treasures',
      travel: 'Paradise Directions',
      faqs: 'Island Info',
      rsvp: 'Join the Luau',
      photos: 'Sunset Snapshots',
    },
    dividerQuote: 'Love blooms brightest by the sea.',
    cornerStyle: '1.5rem',
    tone: 'playful',
    headingStyle: 'script-like',
    cardStyle: 'elevated',
    sectionGradient: 'linear-gradient(135deg, #FFFAF0 0%, #FFF0E0 100%)',
    palette: {
      background: '#FFFAF0',
      foreground: '#0A2E2E',
      accent: '#E87461',
      accent2: '#48B888',
      card: '#FFFDF8',
      muted: '#6A8A8A',
      highlight: '#C85848',
      subtle: '#FFF6EA',
      ink: '#061A1A',
    },
    fonts: { heading: 'Playfair Display', body: 'Poppins' },
    wavePath: WAVE_PATHS['wave'].d,
    wavePathInverted: WAVE_PATHS['wave'].di,
    aiGenerated: false,
  },
  // 21. Winter Wonderland
  {
    name: 'Winter Wonderland',
    curve: 'geometric',
    particle: 'snowflakes',
    accentShape: 'diamond',
    sectionEntrance: 'float',
    texture: 'none',
    decorIcons: ['❄', '✧', '◆', '◎', '✦'],
    accentSymbol: '❄',
    particleColor: '#88c0d8',
    sectionLabels: {
      story: 'A Winter\'s Tale',
      events: 'The Frost Ball',
      registry: 'Snowbound Wishes',
      travel: 'Through the Snow',
      faqs: 'Warming Details',
      rsvp: 'RSVP by Owl Post',
      photos: 'Frozen Memories',
    },
    dividerQuote: 'Love sparkles like fresh-fallen snow.',
    cornerStyle: '0',
    tone: 'dreamy',
    headingStyle: 'thin-elegant',
    cardStyle: 'glass',
    sectionGradient: 'linear-gradient(135deg, #F0F4F8 0%, #E0E8F0 100%)',
    palette: {
      background: '#F0F4F8',
      foreground: '#1C2938',
      accent: '#6BA3BE',
      accent2: '#A0C8D8',
      card: '#F8FAFC',
      muted: '#6A8090',
      highlight: '#4888A8',
      subtle: '#EAF0F6',
      ink: '#0E1820',
    },
    fonts: { heading: 'Cormorant Garamond', body: 'Raleway' },
    wavePath: WAVE_PATHS['geometric'].d,
    wavePathInverted: WAVE_PATHS['geometric'].di,
    aiGenerated: false,
  },
  // 22. Celestial Nocturne
  {
    name: 'Celestial Nocturne',
    curve: 'arch',
    particle: 'stars',
    accentShape: 'infinity',
    sectionEntrance: 'float',
    texture: 'starfield',
    decorIcons: ['✧', '★', '◆', '⟡', '✦'],
    accentSymbol: '⟡',
    particleColor: '#d8c060',
    sectionLabels: {
      story: 'Written in the Stars',
      events: 'A Celestial Gathering',
      registry: 'Starlit Wishes',
      travel: 'Navigate by Stars',
      faqs: 'Cosmic Details',
      rsvp: 'Join Our Constellation',
      photos: 'Astral Memories',
    },
    dividerQuote: 'Two stars destined to share one orbit.',
    cornerStyle: '50% 50% 1.5rem 1.5rem / 3rem 3rem 1.5rem 1.5rem',
    tone: 'cosmic',
    headingStyle: 'uppercase-tracked',
    cardStyle: 'glass',
    sectionGradient: 'linear-gradient(135deg, #0A0E1A 0%, #101828 100%)',
    palette: {
      background: '#0A0E1A',
      foreground: '#F0EBE0',
      accent: '#C8A84A',
      accent2: '#8A7838',
      card: '#0E1424',
      muted: '#6A6880',
      highlight: '#E0C860',
      subtle: '#0C1020',
      ink: '#F8F4E8',
    },
    fonts: { heading: 'Cinzel', body: 'Source Sans 3' },
    wavePath: WAVE_PATHS['arch'].d,
    wavePathInverted: WAVE_PATHS['arch'].di,
    aiGenerated: false,
  },
  // 23. Southern Charm
  {
    name: 'Southern Charm',
    curve: 'petal',
    particle: 'petals',
    accentShape: 'leaf',
    sectionEntrance: 'bloom',
    texture: 'linen',
    decorIcons: ['✿', '❀', '✦', '◎', '❋'],
    accentSymbol: '✿',
    particleColor: '#e8b090',
    sectionLabels: {
      story: 'Sweet Beginnings',
      events: 'The Front Porch Party',
      registry: 'Southern Comforts',
      travel: 'Y\'all Come Now',
      faqs: 'Bless Your Heart FAQ',
      rsvp: 'Save Us a Seat',
      photos: 'Porch Swing Portraits',
    },
    dividerQuote: 'Sweet as tea, strong as magnolias.',
    cornerStyle: '40% 40% 2rem 2rem / 3rem 3rem 2rem 2rem',
    tone: 'intimate',
    headingStyle: 'italic-serif',
    cardStyle: 'elevated',
    sectionGradient: 'linear-gradient(135deg, #FFF8F0 0%, #F5ECE0 100%)',
    palette: {
      background: '#FFF8F0',
      foreground: '#2C1810',
      accent: '#E8A87C',
      accent2: '#F0C8A8',
      card: '#FFFCF8',
      muted: '#9A7E68',
      highlight: '#C88058',
      subtle: '#FAF4EC',
      ink: '#1A0E08',
    },
    fonts: { heading: 'Libre Baskerville', body: 'Lora' },
    wavePath: WAVE_PATHS['petal'].d,
    wavePathInverted: WAVE_PATHS['petal'].di,
    aiGenerated: false,
  },
  // 24. Industrial Chic
  {
    name: 'Industrial Chic',
    curve: 'geometric',
    particle: 'stars',
    accentShape: 'diamond',
    sectionEntrance: 'fade-up',
    texture: 'none',
    decorIcons: ['◆', '▪', '✧', '◎', '■'],
    accentSymbol: '◆',
    particleColor: '#c88848',
    sectionLabels: {
      story: 'The Blueprint',
      events: 'The Main Event',
      registry: 'Curated Goods',
      travel: 'Coordinates',
      faqs: 'Fine Print',
      rsvp: 'Mark Your Calendar',
      photos: 'Raw Frames',
    },
    dividerQuote: 'Built from steel, bonded by heart.',
    cornerStyle: '0',
    tone: 'luxurious',
    headingStyle: 'uppercase-tracked',
    cardStyle: 'minimal',
    sectionGradient: 'linear-gradient(135deg, #E8E4E0 0%, #D8D4D0 100%)',
    palette: {
      background: '#E8E4E0',
      foreground: '#1A1A1A',
      accent: '#B87333',
      accent2: '#D4A060',
      card: '#F0ECEB',
      muted: '#7A7470',
      highlight: '#9A5A20',
      subtle: '#E2DEDC',
      ink: '#0A0A0A',
    },
    fonts: { heading: 'Space Grotesk', body: 'Inter' },
    wavePath: WAVE_PATHS['geometric'].d,
    wavePathInverted: WAVE_PATHS['geometric'].di,
    aiGenerated: false,
  },
  // 25. Y2K Reloaded
  {
    name: 'Y2K Reloaded',
    curve: 'cascade',
    particle: 'confetti',
    accentShape: 'ring',
    sectionEntrance: 'bloom',
    texture: 'none',
    decorIcons: ['✦', '★', '◇', '♡', '✧'],
    accentSymbol: '★',
    particleColor: '#FF69B4',
    sectionLabels: {
      story: 'The Story So Far',
      events: 'The Party',
      registry: 'Our Registry',
      travel: 'Getting Here',
      faqs: 'Good to Know',
      rsvp: 'You In?',
      photos: 'Receipts',
    },
    dividerQuote: 'Main character energy only.',
    cornerStyle: '2rem 0 2rem 0',
    tone: 'playful',
    headingStyle: 'bold-editorial',
    cardStyle: 'elevated',
    sectionGradient: 'linear-gradient(135deg, #FFF0F5 0%, #F0E0FF 100%)',
    palette: {
      background: '#FFF0F5',
      foreground: '#1A0020',
      accent: '#FF69B4',
      accent2: '#40C4FF',
      card: '#FFFFFF',
      muted: '#9A7AAA',
      highlight: '#E040FB',
      subtle: '#FFF5FA',
      ink: '#0A0010',
    },
    fonts: { heading: 'Rubik', body: 'Space Grotesk' },
    wavePath: WAVE_PATHS['cascade'].d,
    wavePathInverted: WAVE_PATHS['cascade'].di,
    aiGenerated: false,
  },
  // 26. Aged to Perfection
  {
    name: 'Aged to Perfection',
    curve: 'organic',
    particle: 'fireflies',
    accentShape: 'leaf',
    sectionEntrance: 'fade-up',
    texture: 'linen',
    decorIcons: ['◆', '✦', '◎', '❋', '✧'],
    accentSymbol: '◆',
    particleColor: '#C4956A',
    sectionLabels: {
      story: 'The Vintage Years',
      events: 'The Tasting',
      registry: 'Our Registry',
      travel: 'Getting Here',
      faqs: 'Good to Know',
      rsvp: 'RSVP',
      photos: 'Through the Years',
    },
    dividerQuote: 'Like fine wine, only better with time.',
    cornerStyle: '3rem 1rem 3rem 1rem',
    tone: 'intimate',
    headingStyle: 'italic-serif',
    cardStyle: 'elevated',
    sectionGradient: 'linear-gradient(135deg, #FAF5F0 0%, #F0E8DC 100%)',
    palette: {
      background: '#FAF5F0',
      foreground: '#2A1810',
      accent: '#722F37',
      accent2: '#C4956A',
      card: '#FFFAF5',
      muted: '#8A7068',
      highlight: '#5A1A22',
      subtle: '#F5F0EA',
      ink: '#1A0C08',
    },
    fonts: { heading: 'Cormorant Garamond', body: 'Lora' },
    wavePath: WAVE_PATHS['organic'].d,
    wavePathInverted: WAVE_PATHS['organic'].di,
    aiGenerated: false,
  },
  // 27. Future Noir
  {
    name: 'Future Noir',
    curve: 'geometric',
    particle: 'stars',
    accentShape: 'diamond',
    sectionEntrance: 'reveal',
    texture: 'starfield',
    decorIcons: ['▮', '◆', '✧', '▪', '◇'],
    accentSymbol: '▮',
    particleColor: '#00D4FF',
    sectionLabels: {
      story: 'Origin Story',
      events: 'The Upload',
      registry: 'Our Registry',
      travel: 'Getting Here',
      faqs: 'Good to Know',
      rsvp: 'Transmit RSVP',
      photos: 'Memory Bank',
    },
    dividerQuote: 'The future starts tonight.',
    cornerStyle: '0.5rem',
    tone: 'cosmic',
    headingStyle: 'uppercase-tracked',
    cardStyle: 'glass',
    sectionGradient: 'linear-gradient(135deg, #0A0A12 0%, #10101E 100%)',
    palette: {
      background: '#0A0A12',
      foreground: '#E0E8F0',
      accent: '#00D4FF',
      accent2: '#7B2FBE',
      card: '#12121E',
      muted: '#6A7A8A',
      highlight: '#00FFD4',
      subtle: '#0E0E18',
      ink: '#F0F4F8',
    },
    fonts: { heading: 'Orbitron', body: 'Inter' },
    wavePath: WAVE_PATHS['geometric'].d,
    wavePathInverted: WAVE_PATHS['geometric'].di,
    aiGenerated: false,
  },
  // 28. Martini Hour
  {
    name: 'Martini Hour',
    curve: 'arch',
    particle: 'stars',
    accentShape: 'diamond',
    sectionEntrance: 'fade-up',
    texture: 'none',
    decorIcons: ['◇', '✧', '◆', '★', '✦'],
    accentSymbol: '◇',
    particleColor: '#D4A800',
    sectionLabels: {
      story: 'The Chronicles',
      events: 'The Soirée',
      registry: 'Our Registry',
      travel: 'Getting Here',
      faqs: 'Good to Know',
      rsvp: 'Raise Your Glass',
      photos: 'Snapshots',
    },
    dividerQuote: 'Shaken, stirred, and celebrated.',
    cornerStyle: '50% 50% 1rem 1rem / 2rem 2rem 1rem 1rem',
    tone: 'luxurious',
    headingStyle: 'italic-serif',
    cardStyle: 'elevated',
    sectionGradient: 'linear-gradient(135deg, #FFFDE8 0%, #FFF8C0 100%)',
    palette: {
      background: '#FFFDE8',
      foreground: '#1A1A0A',
      accent: '#D4A800',
      accent2: '#F0D860',
      card: '#FFFFFF',
      muted: '#9A9470',
      highlight: '#B89000',
      subtle: '#FFFAE0',
      ink: '#0A0A00',
    },
    fonts: { heading: 'Playfair Display', body: 'DM Sans' },
    wavePath: WAVE_PATHS['arch'].d,
    wavePathInverted: WAVE_PATHS['arch'].di,
    aiGenerated: false,
  },
  // 29. Gothic Masquerade
  {
    name: 'Gothic Masquerade',
    curve: 'arch',
    particle: 'fireflies',
    accentShape: 'infinity',
    sectionEntrance: 'float',
    texture: 'starfield',
    decorIcons: ['❖', '✧', '◆', '✦', '☆'],
    accentSymbol: '❖',
    particleColor: '#8B0000',
    sectionLabels: {
      story: 'The Legend',
      events: 'The Grand Affair',
      registry: 'Our Registry',
      travel: 'Getting Here',
      faqs: 'Good to Know',
      rsvp: 'Accept Your Invitation',
      photos: 'Unmasked',
    },
    dividerQuote: 'Behind every mask, a story untold.',
    cornerStyle: '4rem 0 4rem 0 / 2rem 0 2rem 0',
    tone: 'cosmic',
    headingStyle: 'thin-elegant',
    cardStyle: 'glass',
    sectionGradient: 'linear-gradient(135deg, #0D0A10 0%, #180E1A 100%)',
    palette: {
      background: '#0D0A10',
      foreground: '#E8E0F0',
      accent: '#8B0000',
      accent2: '#4A0028',
      card: '#151218',
      muted: '#7A6888',
      highlight: '#C00020',
      subtle: '#100D14',
      ink: '#F0E8F8',
    },
    fonts: { heading: 'Cinzel', body: 'Raleway' },
    wavePath: WAVE_PATHS['arch'].d,
    wavePathInverted: WAVE_PATHS['arch'].di,
    aiGenerated: false,
  },
  // 30. Maximalist Fun House
  {
    name: 'Maximalist Fun House',
    curve: 'cascade',
    particle: 'confetti',
    accentShape: 'ring',
    sectionEntrance: 'bloom',
    texture: 'bokeh',
    decorIcons: ['★', '✦', '◆', '♡', '✧'],
    accentSymbol: '★',
    particleColor: '#FF4444',
    sectionLabels: {
      story: 'The Main Act',
      events: 'Under the Big Top',
      registry: 'Our Registry',
      travel: 'Getting Here',
      faqs: 'Good to Know',
      rsvp: 'Step Right Up',
      photos: 'Showreel',
    },
    dividerQuote: 'More is more and more is everything.',
    cornerStyle: '3rem 0.5rem 3rem 0.5rem',
    tone: 'playful',
    headingStyle: 'bold-editorial',
    cardStyle: 'elevated',
    sectionGradient: 'linear-gradient(135deg, #FFF5F0 0%, #FFE8E0 100%)',
    palette: {
      background: '#FFF5F0',
      foreground: '#1A0A20',
      accent: '#FF4444',
      accent2: '#FFB800',
      card: '#FFFFFF',
      muted: '#9A7A6A',
      highlight: '#4444FF',
      subtle: '#FFF0EB',
      ink: '#100818',
    },
    fonts: { heading: 'Syne', body: 'Quicksand' },
    wavePath: WAVE_PATHS['cascade'].d,
    wavePathInverted: WAVE_PATHS['cascade'].di,
    aiGenerated: false,
  },
];

// ── Label style ───────────────────────────────────────────────
const lbl: React.CSSProperties = {
  display: 'block', fontSize: '0.6rem', fontWeight: 800,
  letterSpacing: '0.16em', textTransform: 'uppercase',
  color: '#71717A', marginBottom: '0.45rem',
};

export function ThemeSwitcher({ currentVibeSkin, onApply }: ThemeSwitcherProps) {
  const [selected, setSelected] = useState<string | null>(null);
  const [hoveredName, setHoveredName] = useState<string | null>(null);

  // Determine which preset (if any) is currently active
  const activePresetName = PRESET_THEMES.find(
    t => t.fonts.heading === currentVibeSkin?.fonts?.heading &&
         t.fonts.body === currentVibeSkin?.fonts?.body &&
         t.palette.background === currentVibeSkin?.palette?.background
  )?.name ?? null;

  const pendingName = selected ?? activePresetName;

  const handleApply = () => {
    const theme = PRESET_THEMES.find(t => t.name === pendingName);
    if (theme) {
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      const { name: _name, ...skin } = theme;
      onApply(skin);
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
        <div style={{ flex: 1, height: '1px', background: 'rgba(0,0,0,0.05)' }} />
        <span style={lbl}>Choose a Theme</span>
        <div style={{ flex: 1, height: '1px', background: 'rgba(0,0,0,0.05)' }} />
      </div>

      {/* Horizontal scroll row */}
      <div style={{
        display: 'flex',
        gap: '8px',
        overflowX: 'auto',
        WebkitOverflowScrolling: 'touch',
        scrollbarWidth: 'none',
        paddingBottom: '4px',
        margin: '0 -4px',
        padding: '0 4px 4px',
      } as React.CSSProperties}>
        {PRESET_THEMES.map((theme) => {
          const isActive = theme.name === (activePresetName);
          const isSelected = theme.name === pendingName;
          const isHovered = hoveredName === theme.name;

          return (
            <motion.button
              key={theme.name}
              onClick={() => setSelected(theme.name)}
              initial={{ opacity: 0, y: 6 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.3, delay: PRESET_THEMES.indexOf(theme) * 0.04, ease: [0.16, 1, 0.3, 1] }}
              whileHover={{ scale: 1.04, y: -1 }}
              whileTap={{ scale: 0.97 }}
              style={{
                flex: '0 0 auto', width: '120px',
                display: 'flex', flexDirection: 'column', alignItems: 'stretch',
                padding: 0, borderRadius: '8px', border: 'none', cursor: 'pointer',
                background: '#FFFFFF',
                outline: isSelected
                  ? '2px solid #6b7c3f'
                  : isHovered ? '1px solid #71717A' : '1px solid rgba(0,0,0,0.05)',
                overflow: 'hidden',
                boxShadow: isSelected ? '0 0 0 3px rgba(107,124,63,0.3)' : isHovered ? '0 4px 16px rgba(0,0,0,0.06)' : '0 1px 4px rgba(0,0,0,0.03)',
                transition: 'outline 0.15s, box-shadow 0.15s',
                position: 'relative',
              }}
            >
              {/* Color swatch strip */}
              <div style={{
                display: 'flex', height: '40px',
              }}>
                <div style={{ flex: 3, background: theme.palette.background }} />
                <div style={{ flex: 1, background: theme.palette.accent }} />
                <div style={{ flex: 1, background: theme.palette.accent2 }} />
              </div>

              {/* Theme info */}
              <div style={{
                padding: '6px 7px', textAlign: 'left',
                background: isSelected ? '#F4F4F5' : 'transparent',
              }}>
                <div style={{
                  fontSize: '0.7rem', fontWeight: 700,
                  color: isSelected ? '#b4c87a' : '#18181B',
                  lineHeight: 1.3, marginBottom: '1px',
                  whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis',
                }}>
                  {theme.name}
                </div>
                <div style={{
                  fontSize: '0.6rem', color: '#71717A',
                  lineHeight: 1.3,
                  whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis',
                }}>
                  {theme.fonts.heading}
                </div>
              </div>

              {/* Active badge */}
              {isActive && (
                <div style={{
                  position: 'absolute', top: '4px', right: '4px',
                  fontSize: '0.62rem', fontWeight: 800, letterSpacing: '0.08em',
                  textTransform: 'uppercase',
                  background: '#6b7c3f', color: '#fff',
                  padding: '2px 5px', borderRadius: '3px',
                }}>
                  Active
                </div>
              )}
            </motion.button>
          );
        })}
      </div>

      {/* Apply button */}
      <motion.button
        onClick={handleApply}
        disabled={!pendingName}
        whileHover={pendingName ? { scale: 1.02, boxShadow: '0 6px 20px rgba(107,124,63,0.4)' } : {}}
        whileTap={pendingName ? { scale: 0.98 } : {}}
        style={{
          display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '6px',
          padding: '9px 16px', borderRadius: '8px', border: 'none', cursor: pendingName ? 'pointer' : 'not-allowed',
          background: pendingName ? 'linear-gradient(135deg, #6b7c3f, #8a9e56)' : 'rgba(0,0,0,0.04)',
          color: pendingName ? '#fff' : '#71717A',
          fontSize: '0.78rem', fontWeight: 700, letterSpacing: '0.04em',
          transition: 'background 0.15s',
          opacity: pendingName ? 1 : 0.6,
        }}
      >
        Apply Theme
      </motion.button>


    </div>
  );
}
