/* Pearloom — theme catalog. LITERAL PORT of
   src/components/pearloom/site/themes.ts (THEMES + themeRootStyle).
   Each theme is a complete --t-* token bag: palette + material
   texture + type pairing + radii + shadows. */

window.PL_THEMES = [
  {
    id: 'santorini', name: 'Santorini Linen',
    blurb: 'Sun-bleached linen, Aegean blue, whitewash & olive.',
    swatches: ['#3F6E92', '#283D4E', '#C2A165', '#EDE7DA'],
    texture: 'linen', motif: 'olive',
    look: { card: 'frame', button: 'square', divider: 'sprig', photo: 'arch', heroAlign: 'center', motifDensity: 'sparse' },
    vars: {
      '--t-paper': '#F5F1E8', '--t-section': '#EDE7DA', '--t-card': '#FBF9F3',
      '--t-ink': '#283D4E', '--t-ink-soft': '#4A6076', '--t-ink-muted': '#8A9AA6',
      '--t-accent': '#3F6E92', '--t-accent-2': '#7C9BB0', '--t-accent-bg': '#E2EAEF', '--t-accent-ink': '#2C5571',
      '--t-gold': '#C2A165', '--t-line': 'rgba(40,61,78,0.16)', '--t-line-soft': 'rgba(40,61,78,0.08)',
      '--t-rsvp': '#283D4E', '--t-rsvp-ink': '#F5F1E8',
      '--t-display': "'Cormorant Garamond', Georgia, serif", '--t-body': "'Inter', sans-serif", '--t-script': "'Caveat', cursive",
      '--t-radius': '5px', '--t-radius-lg': '8px',
      '--t-display-wght': '600', '--t-hero-scale': '1.18', '--t-eyebrow-ls': '0.2em',
      '--t-shadow': '0 1px 0 rgba(40,61,78,0.05)',
    },
  },
  {
    id: 'tuscan', name: 'Tuscan Watercolor',
    blurb: 'Soft washes, terracotta & sage, blooms and lemons.',
    swatches: ['#C2693E', '#8A9A6B', '#C99A4E', '#F4E3D3'],
    texture: 'watercolor', motif: 'bloom',
    look: { card: 'wash', button: 'pill', divider: 'brush', photo: 'tape', heroAlign: 'center', motifDensity: 'generous' },
    vars: {
      '--t-paper': '#FBF6EC', '--t-section': '#F6ECDC', '--t-card': '#FFFCF5',
      '--t-ink': '#4B3D2A', '--t-ink-soft': '#6E5B43', '--t-ink-muted': '#A0907A',
      '--t-accent': '#C2693E', '--t-accent-2': '#D89A6A', '--t-accent-bg': '#F4E3D3', '--t-accent-ink': '#A4502A',
      '--t-gold': '#C99A4E', '--t-line': 'rgba(75,61,42,0.15)', '--t-line-soft': 'rgba(75,61,42,0.08)',
      '--t-rsvp': '#4B3D2A', '--t-rsvp-ink': '#FBF6EC',
      '--t-display': "'Fraunces', Georgia, serif", '--t-body': "'Inter', sans-serif", '--t-script': "'Caveat', cursive",
      '--t-radius': '16px', '--t-radius-lg': '24px',
      '--t-display-wght': '500', '--t-hero-scale': '1', '--t-eyebrow-ls': '0.14em',
      '--t-shadow': '0 14px 30px rgba(75,61,42,0.10)',
    },
  },
  {
    id: 'garden', name: 'Pressed Garden',
    blurb: 'Cotton paper, pressed wildflowers, the Pearloom warmth.',
    swatches: ['#B7A4D0', '#8B9C5A', '#EAB286', '#F3E9D4'],
    texture: 'paper', motif: 'pressed',
    look: { card: 'soft', button: 'pill', divider: 'dot', photo: 'polaroid', heroAlign: 'center', motifDensity: 'generous' },
    vars: {
      '--t-paper': '#FDFAF0', '--t-section': '#F3E9D4', '--t-card': '#FFFEF7',
      '--t-ink': '#3D4A1F', '--t-ink-soft': '#566438', '--t-ink-muted': '#8A8671',
      '--t-accent': '#B7A4D0', '--t-accent-2': '#C4B5D9', '--t-accent-bg': '#E8E0F0', '--t-accent-ink': '#6B5A8C',
      '--t-gold': '#C19A4B', '--t-line': 'rgba(61,74,31,0.14)', '--t-line-soft': 'rgba(61,74,31,0.08)',
      '--t-rsvp': '#3D4A1F', '--t-rsvp-ink': '#F8F1E4',
      '--t-display': "'Fraunces', Georgia, serif", '--t-body': "'Inter', sans-serif", '--t-script': "'Caveat', cursive",
      '--t-radius': '14px', '--t-radius-lg': '22px',
      '--t-display-wght': '600', '--t-hero-scale': '1', '--t-eyebrow-ls': '0.14em',
      '--t-shadow': '0 8px 22px rgba(61,74,31,0.08)',
    },
  },
  {
    id: 'editorial', name: 'Modern Editorial',
    blurb: 'Flat matte, high-contrast type. The clean counterpoint.',
    swatches: ['#1A1A17', '#B08940', '#E9E7E0', '#F4F3EF'],
    texture: 'none', motif: 'none',
    look: { card: 'flat', button: 'sharp', divider: 'rule', photo: 'clean', heroAlign: 'left', motifDensity: 'none' },
    vars: {
      '--t-paper': '#F4F3EF', '--t-section': '#EAE8E1', '--t-card': '#FBFAF7',
      '--t-ink': '#1A1A17', '--t-ink-soft': '#46453E', '--t-ink-muted': '#8A8980',
      '--t-accent': '#1A1A17', '--t-accent-2': '#B08940', '--t-accent-bg': '#E9E7E0', '--t-accent-ink': '#1A1A17',
      '--t-gold': '#B08940', '--t-line': 'rgba(26,26,23,0.16)', '--t-line-soft': 'rgba(26,26,23,0.08)',
      '--t-rsvp': '#1A1A17', '--t-rsvp-ink': '#F4F3EF',
      '--t-display': "'Inter', sans-serif", '--t-body': "'Inter', sans-serif", '--t-script': "'Inter', sans-serif",
      '--t-radius': '2px', '--t-radius-lg': '3px',
      '--t-display-wght': '800', '--t-hero-scale': '1', '--t-eyebrow-ls': '0.24em',
      '--t-shadow': 'none',
    },
  },
  {
    id: 'midnight', name: 'Midnight Velvet',
    blurb: 'Inky velvet, candlelight gold — made for evenings.',
    swatches: ['#1A1B2E', '#C9A24B', '#B9A6E0', '#262842'],
    dark: true, foil: true, texture: 'velvet', motif: 'pressed',
    look: { card: 'soft', button: 'pill', divider: 'dot', photo: 'clean', heroAlign: 'center', motifDensity: 'sparse' },
    vars: {
      '--t-paper': '#1A1B2E', '--t-section': '#20223A', '--t-card': '#262842',
      '--t-ink': '#F1EBDD', '--t-ink-soft': '#C4BDD0', '--t-ink-muted': '#8B86A0',
      '--t-accent': '#B9A6E0', '--t-accent-2': '#C9A24B', '--t-accent-bg': '#2E2C50', '--t-accent-ink': '#D9C9F0',
      '--t-gold': '#C9A24B', '--t-line': 'rgba(241,235,221,0.16)', '--t-line-soft': 'rgba(241,235,221,0.09)',
      '--t-rsvp': '#C9A24B', '--t-rsvp-ink': '#1A1B2E',
      '--t-display': "'Cormorant Garamond', Georgia, serif", '--t-body': "'Inter', sans-serif", '--t-script': "'Caveat', cursive",
      '--t-radius': '12px', '--t-radius-lg': '18px',
      '--t-display-wght': '500', '--t-hero-scale': '1.08', '--t-eyebrow-ls': '0.18em',
      '--t-shadow': '0 16px 40px rgba(0,0,0,0.40)',
    },
  },
  {
    id: 'coastal', name: 'Coastal Ink',
    blurb: 'Deckled paper, navy ink line-work, sea-glass calm.',
    swatches: ['#2C5E7A', '#1F3A4D', '#C9B89A', '#E8E4D6'],
    texture: 'cotton', motif: 'none',
    look: { card: 'frame', button: 'square', divider: 'deckle', photo: 'deckle', heroAlign: 'center', motifDensity: 'none' },
    vars: {
      '--t-paper': '#EAE5D7', '--t-section': '#E0DAC8', '--t-card': '#F4F0E4',
      '--t-ink': '#1F3A4D', '--t-ink-soft': '#3E5B6E', '--t-ink-muted': '#82929E',
      '--t-accent': '#2C5E7A', '--t-accent-2': '#6E93A8', '--t-accent-bg': '#DCE5E7', '--t-accent-ink': '#1F4254',
      '--t-gold': '#B89A5E', '--t-line': 'rgba(31,58,77,0.18)', '--t-line-soft': 'rgba(31,58,77,0.09)',
      '--t-rsvp': '#1F3A4D', '--t-rsvp-ink': '#EAE5D7',
      '--t-display': "'Cormorant Garamond', Georgia, serif", '--t-body': "'Inter', sans-serif", '--t-script': "'Caveat', cursive",
      '--t-radius': '2px', '--t-radius-lg': '3px',
      '--t-display-wght': '600', '--t-hero-scale': '1.12', '--t-eyebrow-ls': '0.22em',
      '--t-shadow': '0 1px 0 rgba(31,58,77,0.06)',
    },
  },
  {
    id: 'amalfi', name: 'Amalfi Citrus',
    blurb: 'Sun-bleached blue, lemon and terracotta — a coastal supper.',
    swatches: ['#2E6B8A', '#C6703D', '#D9B44A', '#FBF6EA'],
    texture: 'linen', motif: 'bloom',
    look: { card: 'frame', button: 'pill', divider: 'sprig', photo: 'arch', heroAlign: 'center', motifDensity: 'generous' },
    vars: {
      '--t-paper': '#FBF6EA', '--t-section': '#F1E7D4', '--t-card': '#FFFCF4',
      '--t-ink': '#1A2A33', '--t-ink-soft': '#3C5560', '--t-ink-muted': '#7E8E96',
      '--t-accent': '#2E6B8A', '--t-accent-2': '#5E94AD', '--t-accent-bg': '#E2EAEF', '--t-accent-ink': '#235874',
      '--t-gold': '#D9B44A', '--t-line': 'rgba(26,42,51,0.16)', '--t-line-soft': 'rgba(26,42,51,0.08)',
      '--t-rsvp': '#C6703D', '--t-rsvp-ink': '#FBF6EA',
      '--t-display': "'Fraunces', Georgia, serif", '--t-body': "'Inter', sans-serif", '--t-script': "'Caveat', cursive",
      '--t-radius': '14px', '--t-radius-lg': '22px',
      '--t-display-wght': '500', '--t-hero-scale': '1.06', '--t-eyebrow-ls': '0.16em',
      '--t-shadow': '0 10px 26px rgba(26,42,51,0.10)',
    },
  },
  {
    id: 'first-light', name: 'First Light',
    blurb: 'Dawn rose and gold — the morning after, every year after.',
    swatches: ['#C6563D', '#C19A4B', '#D9A89E', '#FCF4EE'],
    texture: 'paper', motif: 'pressed',
    look: { card: 'soft', button: 'pill', divider: 'dot', photo: 'polaroid', heroAlign: 'center', motifDensity: 'sparse' },
    vars: {
      '--t-paper': '#FCF4EE', '--t-section': '#F6E4DA', '--t-card': '#FFFBF7',
      '--t-ink': '#3A2A2A', '--t-ink-soft': '#5E4742', '--t-ink-muted': '#9C8780',
      '--t-accent': '#C6563D', '--t-accent-2': '#D9897A', '--t-accent-bg': '#F6DDD4', '--t-accent-ink': '#A63F2A',
      '--t-gold': '#C19A4B', '--t-line': 'rgba(58,42,42,0.14)', '--t-line-soft': 'rgba(58,42,42,0.07)',
      '--t-rsvp': '#C6563D', '--t-rsvp-ink': '#FCF4EE',
      '--t-display': "'Fraunces', Georgia, serif", '--t-body': "'Inter', sans-serif", '--t-script': "'Caveat', cursive",
      '--t-radius': '14px', '--t-radius-lg': '22px',
      '--t-display-wght': '600', '--t-hero-scale': '1', '--t-eyebrow-ls': '0.14em',
      '--t-shadow': '0 8px 22px rgba(58,42,42,0.09)',
    },
  },
  {
    id: 'deco-gilt', name: 'Deco Gilt',
    blurb: 'Jazz-age geometry — ink, gilt and a hard-edged fan.',
    swatches: ['#14110C', '#C9A24B', '#7C8A6A', '#F3ECD9'],
    dark: true, foil: true, texture: 'velvet', motif: 'none',
    look: { card: 'flat', button: 'sharp', divider: 'rule', photo: 'clean', heroAlign: 'left', motifDensity: 'none' },
    vars: {
      '--t-paper': '#14110C', '--t-section': '#1C1810', '--t-card': '#211C13',
      '--t-ink': '#F3ECD9', '--t-ink-soft': '#C9C0A8', '--t-ink-muted': '#8A8266',
      '--t-accent': '#C9A24B', '--t-accent-2': '#7C8A6A', '--t-accent-bg': '#2A2416', '--t-accent-ink': '#E6C977',
      '--t-gold': '#C9A24B', '--t-line': 'rgba(243,236,217,0.16)', '--t-line-soft': 'rgba(243,236,217,0.08)',
      '--t-rsvp': '#C9A24B', '--t-rsvp-ink': '#14110C',
      '--t-display': "'Fraunces', Georgia, serif", '--t-body': "'Geist Mono', ui-monospace, monospace", '--t-script': "'Caveat', cursive",
      '--t-radius': '1px', '--t-radius-lg': '2px',
      '--t-display-wght': '700', '--t-hero-scale': '1.1', '--t-eyebrow-ls': '0.3em',
      '--t-shadow': '0 16px 40px rgba(0,0,0,0.45)',
    },
  },
  {
    id: 'tide-coast', name: 'Tide & Coast',
    blurb: 'Fog, driftwood and rope — an unhurried seaside vow.',
    swatches: ['#5E7A82', '#C8BFA5', '#9DB0B2', '#F2F1EC'],
    texture: 'cotton', motif: 'none',
    look: { card: 'frame', button: 'square', divider: 'deckle', photo: 'deckle', heroAlign: 'center', motifDensity: 'sparse' },
    vars: {
      '--t-paper': '#F2F1EC', '--t-section': '#E6E5DD', '--t-card': '#FAFAF6',
      '--t-ink': '#2C353A', '--t-ink-soft': '#4E5A60', '--t-ink-muted': '#8B969B',
      '--t-accent': '#5E7A82', '--t-accent-2': '#9DB0B2', '--t-accent-bg': '#DEE5E5', '--t-accent-ink': '#46626A',
      '--t-gold': '#B8A580', '--t-line': 'rgba(44,53,58,0.16)', '--t-line-soft': 'rgba(44,53,58,0.08)',
      '--t-rsvp': '#2C353A', '--t-rsvp-ink': '#F2F1EC',
      '--t-display': "'Cormorant Garamond', Georgia, serif", '--t-body': "'Inter', sans-serif", '--t-script': "'Caveat', cursive",
      '--t-radius': '3px', '--t-radius-lg': '5px',
      '--t-display-wght': '600', '--t-hero-scale': '1.12', '--t-eyebrow-ls': '0.2em',
      '--t-shadow': '0 1px 0 rgba(44,53,58,0.06)',
    },
  },

  /* ═══════════ ATELIER COLLECTION — premium themes ═══════════ */
  {
    id: 'provence', name: 'Provence Lavender',
    blurb: 'Lavender rows, warm stone and a laurel hush — Aix in June.',
    swatches: ['#7C6AA6', '#3B3550', '#C2A165', '#ECE6DC'],
    texture: 'linen', motif: 'lavender',
    look: { card: 'frame', button: 'pill', divider: 'laurel', photo: 'arch', heroAlign: 'center', motifDensity: 'generous' },
    vars: {
      '--t-paper': '#F6F2EC', '--t-section': '#ECE6DC', '--t-card': '#FCFAF4',
      '--t-ink': '#3B3550', '--t-ink-soft': '#5C5470', '--t-ink-muted': '#928BA4',
      '--t-accent': '#7C6AA6', '--t-accent-2': '#A99BC8', '--t-accent-bg': '#E7E1F0', '--t-accent-ink': '#5E4E86',
      '--t-gold': '#C2A165', '--t-line': 'rgba(59,53,80,0.15)', '--t-line-soft': 'rgba(59,53,80,0.08)',
      '--t-rsvp': '#3B3550', '--t-rsvp-ink': '#F6F2EC',
      '--t-display': "'Cormorant Garamond', Georgia, serif", '--t-body': "'Inter', sans-serif", '--t-script': "'Caveat', cursive",
      '--t-radius': '8px', '--t-radius-lg': '14px',
      '--t-display-wght': '600', '--t-hero-scale': '1.14', '--t-eyebrow-ls': '0.2em',
      '--t-shadow': '0 10px 26px rgba(59,53,80,0.10)',
    },
  },
  {
    id: 'botanical', name: 'Botanical Press',
    blurb: 'Deep herbarium green, pressed ferns between cotton leaves.',
    swatches: ['#3C5A40', '#243A28', '#C2A04E', '#EEEAD9'],
    texture: 'paper', motif: 'fern',
    look: { card: 'frame', button: 'square', divider: 'laurel', photo: 'polaroid', heroAlign: 'center', motifDensity: 'generous' },
    vars: {
      '--t-paper': '#F1EEDE', '--t-section': '#E6E2CE', '--t-card': '#F8F6EC',
      '--t-ink': '#243A28', '--t-ink-soft': '#42583F', '--t-ink-muted': '#7E8C74',
      '--t-accent': '#3C5A40', '--t-accent-2': '#6E8A66', '--t-accent-bg': '#DDE5D4', '--t-accent-ink': '#2E4A32',
      '--t-gold': '#C2A04E', '--t-line': 'rgba(36,58,40,0.16)', '--t-line-soft': 'rgba(36,58,40,0.08)',
      '--t-rsvp': '#243A28', '--t-rsvp-ink': '#F1EEDE',
      '--t-display': "'Fraunces', Georgia, serif", '--t-body': "'Inter', sans-serif", '--t-script': "'Caveat', cursive",
      '--t-radius': '4px', '--t-radius-lg': '7px',
      '--t-display-wght': '500', '--t-hero-scale': '1.1', '--t-eyebrow-ls': '0.22em',
      '--t-shadow': '0 6px 18px rgba(36,58,40,0.10)',
    },
  },
  {
    id: 'gilded-noir', name: 'Gilded Noir',
    blurb: 'Black tie after dark — onyx velvet struck with champagne gold.',
    swatches: ['#0E0C0A', '#D8B26A', '#9C8552', '#1A1712'],
    dark: true, foil: true, texture: 'velvet', motif: 'deco',
    look: { card: 'flat', button: 'sharp', divider: 'chevron', photo: 'clean', heroAlign: 'left', motifDensity: 'sparse' },
    vars: {
      '--t-paper': '#0E0C0A', '--t-section': '#16130E', '--t-card': '#1C1812',
      '--t-ink': '#F4ECDA', '--t-ink-soft': '#C9BD9F', '--t-ink-muted': '#988B6E',
      '--t-accent': '#D8B26A', '--t-accent-2': '#E8D29A', '--t-accent-bg': '#2A2417', '--t-accent-ink': '#E8CE92',
      '--t-gold': '#D8B26A', '--t-line': 'rgba(216,178,106,0.22)', '--t-line-soft': 'rgba(216,178,106,0.10)',
      '--t-rsvp': '#D8B26A', '--t-rsvp-ink': '#0E0C0A',
      '--t-display': "'Fraunces', Georgia, serif", '--t-body': "'Geist Mono', ui-monospace, monospace", '--t-script': "'Caveat', cursive",
      '--t-radius': '1px', '--t-radius-lg': '2px',
      '--t-display-wght': '600', '--t-hero-scale': '1.16', '--t-eyebrow-ls': '0.32em',
      '--t-shadow': '0 18px 44px rgba(0,0,0,0.5)',
    },
  },
  {
    id: 'blush-atelier', name: 'Blush Atelier',
    blurb: 'Powder blush and rose-gold — a couture fitting in soft light.',
    swatches: ['#C77F8E', '#5A3340', '#C9A05E', '#F7ECEC'],
    texture: 'silk', motif: 'bloom',
    look: { card: 'soft', button: 'pill', divider: 'ribbon', photo: 'arch', heroAlign: 'center', motifDensity: 'generous' },
    vars: {
      '--t-paper': '#FBF3F2', '--t-section': '#F5E6E5', '--t-card': '#FFFAF9',
      '--t-ink': '#5A3340', '--t-ink-soft': '#7C5060', '--t-ink-muted': '#A98390',
      '--t-accent': '#C77F8E', '--t-accent-2': '#DFA9B3', '--t-accent-bg': '#F4E0E2', '--t-accent-ink': '#A85E6E',
      '--t-gold': '#C9A05E', '--t-line': 'rgba(90,51,64,0.14)', '--t-line-soft': 'rgba(90,51,64,0.07)',
      '--t-rsvp': '#5A3340', '--t-rsvp-ink': '#FBF3F2',
      '--t-display': "'Cormorant Garamond', Georgia, serif", '--t-body': "'Inter', sans-serif", '--t-script': "'Dancing Script', cursive",
      '--t-radius': '14px', '--t-radius-lg': '22px',
      '--t-display-wght': '600', '--t-hero-scale': '1.12', '--t-eyebrow-ls': '0.18em',
      '--t-shadow': '0 14px 34px rgba(90,51,64,0.12)',
    },
  },
  {
    id: 'sage-marble', name: 'Sage & Marble',
    blurb: 'Veined marble, sage and a quiet laurel — a sculpted calm.',
    swatches: ['#6E8169', '#33402F', '#B8A878', '#EFEDE6'],
    texture: 'marble', motif: 'laurel',
    look: { card: 'frame', button: 'square', divider: 'arc', photo: 'clean', heroAlign: 'center', motifDensity: 'sparse' },
    vars: {
      '--t-paper': '#F1EFE8', '--t-section': '#E7E5DB', '--t-card': '#FAF9F4',
      '--t-ink': '#33402F', '--t-ink-soft': '#52604C', '--t-ink-muted': '#8B9683',
      '--t-accent': '#6E8169', '--t-accent-2': '#9AAA92', '--t-accent-bg': '#E0E4D8', '--t-accent-ink': '#536650',
      '--t-gold': '#B8A878', '--t-line': 'rgba(51,64,47,0.15)', '--t-line-soft': 'rgba(51,64,47,0.08)',
      '--t-rsvp': '#33402F', '--t-rsvp-ink': '#F1EFE8',
      '--t-display': "'Cormorant Garamond', Georgia, serif", '--t-body': "'Inter', sans-serif", '--t-script': "'Caveat', cursive",
      '--t-radius': '3px', '--t-radius-lg': '6px',
      '--t-display-wght': '600', '--t-hero-scale': '1.15', '--t-eyebrow-ls': '0.24em',
      '--t-shadow': '0 8px 24px rgba(51,64,47,0.09)',
    },
  },
  {
    id: 'terracotta-sun', name: 'Terracotta Sun',
    blurb: 'Warm clay, ochre and a low sun — a courtyard at golden hour.',
    swatches: ['#C2673B', '#5A2E1B', '#D29B3F', '#F6E9DA'],
    texture: 'cotton', motif: 'sun',
    look: { card: 'wash', button: 'pill', divider: 'rays', photo: 'tape', heroAlign: 'center', motifDensity: 'generous' },
    vars: {
      '--t-paper': '#FAEEDF', '--t-section': '#F2E0CC', '--t-card': '#FFF8EF',
      '--t-ink': '#5A2E1B', '--t-ink-soft': '#7E4C32', '--t-ink-muted': '#A87E62',
      '--t-accent': '#C2673B', '--t-accent-2': '#DB9460', '--t-accent-bg': '#F4DCC6', '--t-accent-ink': '#A2502A',
      '--t-gold': '#D29B3F', '--t-line': 'rgba(90,46,27,0.15)', '--t-line-soft': 'rgba(90,46,27,0.08)',
      '--t-rsvp': '#5A2E1B', '--t-rsvp-ink': '#FAEEDF',
      '--t-display': "'Fraunces', Georgia, serif", '--t-body': "'Inter', sans-serif", '--t-script': "'Caveat', cursive",
      '--t-radius': '12px', '--t-radius-lg': '20px',
      '--t-display-wght': '500', '--t-hero-scale': '1.1', '--t-eyebrow-ls': '0.16em',
      '--t-shadow': '0 12px 28px rgba(90,46,27,0.12)',
    },
  },
  {
    id: 'ink-botanical', name: 'Ink Botanical',
    blurb: 'Navy line-work ferns on sea-cotton — an engraver\u2019s garden.',
    swatches: ['#26415A', '#16283A', '#B79A5E', '#E9E6DB'],
    texture: 'cotton', motif: 'fern',
    look: { card: 'frame', button: 'square', divider: 'wave', photo: 'deckle', heroAlign: 'center', motifDensity: 'sparse' },
    vars: {
      '--t-paper': '#ECE9DE', '--t-section': '#E2DFD1', '--t-card': '#F6F4EA',
      '--t-ink': '#16283A', '--t-ink-soft': '#35495E', '--t-ink-muted': '#73849A',
      '--t-accent': '#26415A', '--t-accent-2': '#5E7790', '--t-accent-bg': '#D8E0E8', '--t-accent-ink': '#1E3650',
      '--t-gold': '#B79A5E', '--t-line': 'rgba(22,40,58,0.16)', '--t-line-soft': 'rgba(22,40,58,0.08)',
      '--t-rsvp': '#16283A', '--t-rsvp-ink': '#ECE9DE',
      '--t-display': "'Cormorant Garamond', Georgia, serif", '--t-body': "'Inter', sans-serif", '--t-script': "'Caveat', cursive",
      '--t-radius': '3px', '--t-radius-lg': '5px',
      '--t-display-wght': '600', '--t-hero-scale': '1.12', '--t-eyebrow-ls': '0.22em',
      '--t-shadow': '0 1px 0 rgba(22,40,58,0.06)',
    },
  },
  {
    id: 'champagne-deco', name: 'Champagne Deco',
    blurb: 'Cream and gilt geometry — a Gatsby parlor at half past ten.',
    swatches: ['#B89248', '#2A2418', '#8A7038', '#F4EEDD'],
    texture: 'none', motif: 'deco',
    look: { card: 'flat', button: 'sharp', divider: 'chevron', photo: 'clean', heroAlign: 'left', motifDensity: 'sparse' },
    vars: {
      '--t-paper': '#F4EEDD', '--t-section': '#ECE4CF', '--t-card': '#FBF7EA',
      '--t-ink': '#2A2418', '--t-ink-soft': '#4C4330', '--t-ink-muted': '#8A7E62',
      '--t-accent': '#B89248', '--t-accent-2': '#D2B878', '--t-accent-bg': '#EBE0C4', '--t-accent-ink': '#917130',
      '--t-gold': '#B89248', '--t-line': 'rgba(42,36,24,0.16)', '--t-line-soft': 'rgba(42,36,24,0.08)',
      '--t-rsvp': '#2A2418', '--t-rsvp-ink': '#F4EEDD',
      '--t-display': "'Fraunces', Georgia, serif", '--t-body': "'Geist Mono', ui-monospace, monospace", '--t-script': "'Caveat', cursive",
      '--t-radius': '1px', '--t-radius-lg': '2px',
      '--t-display-wght': '700', '--t-hero-scale': '1.14', '--t-eyebrow-ls': '0.3em',
      '--t-shadow': '0 2px 0 rgba(42,36,24,0.06)',
    },
  },
  {
    id: 'moss-velvet', name: 'Moss Velvet',
    blurb: 'Deep forest velvet and brass — an evening among the pines.',
    swatches: ['#2C3A2A', '#C7A86A', '#A9BE8E', '#1E281C'],
    dark: true, foil: true, texture: 'velvet', motif: 'fern',
    look: { card: 'soft', button: 'pill', divider: 'laurel', photo: 'clean', heroAlign: 'center', motifDensity: 'sparse' },
    vars: {
      '--t-paper': '#1A231A', '--t-section': '#212C20', '--t-card': '#28331F',
      '--t-ink': '#EDEEDF', '--t-ink-soft': '#C3CBB0', '--t-ink-muted': '#93A07E',
      '--t-accent': '#C7A86A', '--t-accent-2': '#A9BE8E', '--t-accent-bg': '#2E3A24', '--t-accent-ink': '#D8BE84',
      '--t-gold': '#C7A86A', '--t-line': 'rgba(237,238,223,0.16)', '--t-line-soft': 'rgba(237,238,223,0.08)',
      '--t-rsvp': '#C7A86A', '--t-rsvp-ink': '#1A231A',
      '--t-display': "'Cormorant Garamond', Georgia, serif", '--t-body': "'Inter', sans-serif", '--t-script': "'Caveat', cursive",
      '--t-radius': '10px', '--t-radius-lg': '16px',
      '--t-display-wght': '600', '--t-hero-scale': '1.14', '--t-eyebrow-ls': '0.2em',
      '--t-shadow': '0 16px 38px rgba(0,0,0,0.42)',
    },
  },
  {
    id: 'coral-sea', name: 'Coral & Sea',
    blurb: 'Living coral against teal shallows — a reef-bright welcome.',
    swatches: ['#E0735C', '#1F5560', '#E2B85C', '#F3EFE4'],
    texture: 'linen', motif: 'wave',
    look: { card: 'frame', button: 'pill', divider: 'wave', photo: 'arch', heroAlign: 'center', motifDensity: 'generous' },
    vars: {
      '--t-paper': '#F4F0E5', '--t-section': '#E8E8DA', '--t-card': '#FCFAF1',
      '--t-ink': '#1F4048', '--t-ink-soft': '#3E5C63', '--t-ink-muted': '#7C949A',
      '--t-accent': '#E0735C', '--t-accent-2': '#3E8A93', '--t-accent-bg': '#F5DAD2', '--t-accent-ink': '#C2543E',
      '--t-gold': '#E2B85C', '--t-line': 'rgba(31,64,72,0.15)', '--t-line-soft': 'rgba(31,64,72,0.08)',
      '--t-rsvp': '#1F5560', '--t-rsvp-ink': '#F4F0E5',
      '--t-display': "'Fraunces', Georgia, serif", '--t-body': "'Inter', sans-serif", '--t-script': "'Caveat', cursive",
      '--t-radius': '7px', '--t-radius-lg': '12px',
      '--t-display-wght': '500', '--t-hero-scale': '1.12', '--t-eyebrow-ls': '0.18em',
      '--t-shadow': '0 10px 26px rgba(31,64,72,0.10)',
    },
  },
  {
    id: 'plum-romance', name: 'Plum Romance',
    blurb: 'Plum peonies bleeding into dusty rose — a velvet evening vow.',
    swatches: ['#7E4368', '#3A2034', '#C19A6B', '#F4ECEF'],
    texture: 'watercolor', motif: 'bloom',
    look: { card: 'wash', button: 'pill', divider: 'ribbon', photo: 'tape', heroAlign: 'center', motifDensity: 'generous' },
    vars: {
      '--t-paper': '#F6EEF1', '--t-section': '#EEE0E6', '--t-card': '#FCF7F9',
      '--t-ink': '#3A2034', '--t-ink-soft': '#5E3F54', '--t-ink-muted': '#967986',
      '--t-accent': '#7E4368', '--t-accent-2': '#A86E92', '--t-accent-bg': '#EDDBE5', '--t-accent-ink': '#6A3556',
      '--t-gold': '#C19A6B', '--t-line': 'rgba(58,32,52,0.14)', '--t-line-soft': 'rgba(58,32,52,0.07)',
      '--t-rsvp': '#3A2034', '--t-rsvp-ink': '#F6EEF1',
      '--t-display': "'Cormorant Garamond', Georgia, serif", '--t-body': "'Inter', sans-serif", '--t-script': "'Dancing Script', cursive",
      '--t-radius': '14px', '--t-radius-lg': '22px',
      '--t-display-wght': '600', '--t-hero-scale': '1.12', '--t-eyebrow-ls': '0.16em',
      '--t-shadow': '0 14px 32px rgba(58,32,52,0.12)',
    },
  },
  {
    id: 'golden-hour', name: 'Golden Hour',
    blurb: 'Amber light spilling long across the field — the last warm hour.',
    swatches: ['#D88A3A', '#5A3A1E', '#C9A14A', '#FBF0DD'],
    texture: 'paper', motif: 'sun',
    look: { card: 'soft', button: 'pill', divider: 'rays', photo: 'polaroid', heroAlign: 'center', motifDensity: 'generous' },
    vars: {
      '--t-paper': '#FCF2E0', '--t-section': '#F6E6CC', '--t-card': '#FFFBF2',
      '--t-ink': '#5A3A1E', '--t-ink-soft': '#7E5836', '--t-ink-muted': '#AB8A64',
      '--t-accent': '#D88A3A', '--t-accent-2': '#E8AE66', '--t-accent-bg': '#F7E2C4', '--t-accent-ink': '#B26C24',
      '--t-gold': '#C9A14A', '--t-line': 'rgba(90,58,30,0.15)', '--t-line-soft': 'rgba(90,58,30,0.08)',
      '--t-rsvp': '#5A3A1E', '--t-rsvp-ink': '#FCF2E0',
      '--t-display': "'Fraunces', Georgia, serif", '--t-body': "'Inter', sans-serif", '--t-script': "'Caveat', cursive",
      '--t-radius': '11px', '--t-radius-lg': '18px',
      '--t-display-wght': '500', '--t-hero-scale': '1.12', '--t-eyebrow-ls': '0.16em',
      '--t-shadow': '0 12px 28px rgba(90,58,30,0.12)',
    },
  },
];

window.PL_DEFAULT_THEME_ID = 'garden';
window.PL_getTheme = function (id) {
  return window.PL_THEMES.find((t) => t.id === id)
    || window.PL_THEMES.find((t) => t.id === window.PL_DEFAULT_THEME_ID)
    || window.PL_THEMES[0];
};

window.PL_PAD_BY_DENSITY = { cozy: 0.74, comfortable: 1, spacious: 1.32 };

/* Full theme ROOT style — the --t-* set PLUS the base design-system
   vars shadowed to the theme's values, so any markup referencing
   base tokens re-skins for free. Port of themeRootStyle(). */
window.PL_themeRootStyle = function (theme, density, override) {
  const v = (override && Object.keys(override).length) ? Object.assign({}, theme.vars, override) : theme.vars;
  const pad = window.PL_PAD_BY_DENSITY[density] || 1;
  return Object.assign({}, v, {
    '--t-pad': pad,
    '--paper': v['--t-paper'], '--card': v['--t-card'],
    '--ink': v['--t-ink'], '--ink-soft': v['--t-ink-soft'], '--ink-muted': v['--t-ink-muted'],
    '--cream': v['--t-paper'], '--cream-2': v['--t-section'], '--cream-3': v['--t-section'],
    '--line': v['--t-line'], '--line-soft': v['--t-line-soft'], '--card-ring': v['--t-line-soft'],
    '--font-display': v['--t-display'], '--gold': v['--t-gold'],
    '--t-mono': "'Geist Mono', ui-monospace, monospace",
    fontFamily: v['--t-body'], color: v['--t-ink'], background: v['--t-paper'],
  });
};
