'use client';

// ─────────────────────────────────────────────────────────────
// Pearloom / components/guest-experience/PersonalGuestHero.tsx
//
// The first-person hero for /g/{token}. Animates the guest's
// name into view over a softly-lit theme-colored field, then
// reveals the hero copy generated by Claude. Designed to feel
// like opening a personal letter — not a website banner.
// ─────────────────────────────────────────────────────────────

import { useEffect, useState } from 'react';
import { Monogram, type MonogramFrame } from '@/components/pearloom/site/Monogram';

interface PersonalGuestHeroProps {
  guestFirstName: string;
  coupleNames: [string, string];
  heroCopy: string;
  accent: string;
  headingFont: string;
  eventDate: string;
  venue: string;
  /** Couple's crest — manifest.monogram or names-derived. Rendered
   *  as a watermark above the greeting so the passport opens the
   *  way the couple's stationery does. */
  monogram?: { initials: string; frame: MonogramFrame };
}

function formatDate(iso: string): string {
  if (!iso) return '';
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleDateString(undefined, {
    weekday: 'long',
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  });
}

export function PersonalGuestHero({
  guestFirstName,
  coupleNames,
  heroCopy,
  accent,
  headingFont,
  eventDate,
  venue,
  monogram,
}: PersonalGuestHeroProps) {
  const [mounted, setMounted] = useState(false);
  useEffect(() => {
    const t = setTimeout(() => setMounted(true), 60);
    return () => clearTimeout(t);
  }, []);

  const coupleLine = coupleNames.filter(Boolean).join(' & ');
  const prettyDate = formatDate(eventDate);

  /* Accent ink — the host's live accent, not the prototype peach.
     Falls back to peach only when the page passes nothing. */
  const peachInk = accent || '#C6703D';
  return (
    <header
      style={{
        position: 'relative',
        padding: 'calc(80px * var(--pl-density-scale, 1)) 24px calc(56px * var(--pl-density-scale, 1))',
        textAlign: 'center',
        overflow: 'hidden',
      }}
    >
      {/* Soft radial accent wash */}
      <div
        aria-hidden
        style={{
          position: 'absolute',
          inset: 0,
          background: `radial-gradient(ellipse at 50% 10%, ${accent}22 0%, transparent 60%)`,
          pointerEvents: 'none',
        }}
      />

      <div
        style={{
          position: 'relative',
          maxWidth: 760,
          margin: '0 auto',
          opacity: mounted ? 1 : 0,
          transform: mounted ? 'translateY(0)' : 'translateY(12px)',
          transition: 'opacity 900ms ease, transform 900ms ease',
        }}
      >
        {/* Couple's monogram — watermark variant, settled above the
            greeting like a letterhead crest. Binds to --t-accent via
            the shared Monogram component, so it recolors with the
            site's pack. */}
        {monogram && (
          <div
            aria-hidden="true"
            style={{ display: 'flex', justifyContent: 'center', marginBottom: 4 }}
          >
            <Monogram
              initials={monogram.initials}
              frame={monogram.frame}
              size={84}
              withCard={false}
              ariaHidden
            />
          </div>
        )}

        {/* Eyebrow — peach editorial kicker matching the themed
            renderer's section heads. */}
        <div
          className="eyebrow"
          style={{
            textTransform: 'uppercase',
            letterSpacing: '0.22em',
            fontSize: 11,
            fontWeight: 700,
            color: peachInk,
            marginBottom: 18,
          }}
        >
          A letter for {guestFirstName}
        </div>

        {/* Display H1 — name in upright Fraunces, then italic
            "you're invited." in peach. Matches the prototype's
            two-tier hero typography. */}
        <h1
          style={{
            fontFamily: headingFont,
            fontSize: 'calc(clamp(40px, 7cqw, 76px) * var(--pl-hero-scale, 1))',
            lineHeight: 0.98,
            letterSpacing: '-0.02em',
            margin: 0,
            marginBottom: 22,
            fontWeight: 'var(--pl-display-wght, 600)',
          }}
        >
          {guestFirstName},
          <br />
          <span style={{ fontStyle: 'italic', fontWeight: 400, color: peachInk }}>
            you&apos;re invited.
          </span>
        </h1>

        {/* Tagline — italic display, not body — so it reads as a
            handwritten note rather than marketing copy. */}
        <p
          style={{
            fontFamily: headingFont,
            fontStyle: 'italic',
            fontWeight: 400,
            fontSize: 'clamp(17px, 2.1cqw, 21px)',
            lineHeight: 1.5,
            maxWidth: 560,
            margin: '0 auto 28px',
            color: 'var(--ink-soft, #3A332C)',
          }}
        >
          {heroCopy}
        </p>

        {/* Gold hairline above the couple plate */}
        <div
          aria-hidden
          style={{
            width: 160,
            height: 1,
            margin: '0 auto 22px',
            background: 'linear-gradient(90deg, transparent, var(--t-gold, #C19A4B) 50%, transparent)',
            opacity: 0.55,
          }}
        />

        {/* Couple + date plate — italic couple line on top, eyebrow
            meta beneath. */}
        <div
          style={{
            display: 'inline-flex',
            flexDirection: 'column',
            gap: 8,
            alignItems: 'center',
          }}
        >
          <span
            style={{
              fontFamily: headingFont,
              fontStyle: 'italic',
              fontSize: 22,
              fontWeight: 500,
              color: 'var(--ink, #0E0D0B)',
              letterSpacing: '-0.01em',
            }}
          >
            {coupleLine}
          </span>
          {(prettyDate || venue) && (
            <span
              className="eyebrow"
              style={{
                textTransform: 'uppercase',
                letterSpacing: '0.22em',
                fontSize: 10.5,
                fontWeight: 700,
                color: 'var(--ink-muted, #6F6557)',
              }}
            >
              {[prettyDate, venue].filter(Boolean).join(' · ')}
            </span>
          )}
        </div>
      </div>
    </header>
  );
}
