'use client';

// ─────────────────────────────────────────────────────────────
// Pearloom / components/guest-experience/PersonalGuestHero.tsx
//
// The first-person hero for /g/{token}. Animates the guest's
// name into view over a softly-lit theme-colored field, then
// reveals the hero copy generated by Claude. Designed to feel
// like opening a personal letter — not a website banner.
// ─────────────────────────────────────────────────────────────

import { useEffect, useState } from 'react';

interface PersonalGuestHeroProps {
  guestFirstName: string;
  coupleNames: [string, string];
  heroCopy: string;
  accent: string;
  headingFont: string;
  eventDate: string;
  venue: string;
}

function formatDate(iso: string): string {
  if (!iso) return '';
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleDateString(undefined, {
    weekday: 'long',
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  });
}

export function PersonalGuestHero({
  guestFirstName,
  coupleNames,
  heroCopy,
  accent,
  headingFont,
  eventDate,
  venue,
}: PersonalGuestHeroProps) {
  const [mounted, setMounted] = useState(false);
  useEffect(() => {
    const t = setTimeout(() => setMounted(true), 60);
    return () => clearTimeout(t);
  }, []);

  const coupleLine = coupleNames.filter(Boolean).join(' & ');
  const prettyDate = formatDate(eventDate);

  return (
    <header
      style={{
        position: 'relative',
        padding: '6rem 1.5rem 4rem',
        textAlign: 'center',
        overflow: 'hidden',
      }}
    >
      {/* Soft radial accent wash */}
      <div
        aria-hidden
        style={{
          position: 'absolute',
          inset: 0,
          background: `radial-gradient(ellipse at 50% 10%, ${accent}22 0%, transparent 60%)`,
          pointerEvents: 'none',
        }}
      />

      <div
        style={{
          position: 'relative',
          maxWidth: 760,
          margin: '0 auto',
          opacity: mounted ? 1 : 0,
          transform: mounted ? 'translateY(0)' : 'translateY(12px)',
          transition: 'opacity 900ms ease, transform 900ms ease',
        }}
      >
        <div
          style={{
            textTransform: 'uppercase',
            letterSpacing: '0.22em',
            fontSize: '0.72rem',
            opacity: 0.7,
            marginBottom: '1.25rem',
          }}
        >
          A letter for {guestFirstName}
        </div>

        <h1
          style={{
            fontFamily: headingFont,
            fontSize: 'clamp(2.4rem, 6vw, 4.25rem)',
            lineHeight: 1.05,
            letterSpacing: '-0.02em',
            margin: 0,
            marginBottom: '1.5rem',
            fontWeight: 500,
          }}
        >
          {guestFirstName},
          <br />
          <span style={{ color: accent }}>you're invited.</span>
        </h1>

        <p
          style={{
            fontSize: 'clamp(1.02rem, 2.1vw, 1.2rem)',
            lineHeight: 1.6,
            maxWidth: 560,
            margin: '0 auto 2rem',
            opacity: 0.92,
          }}
        >
          {heroCopy}
        </p>

        <div
          style={{
            display: 'inline-flex',
            flexDirection: 'column',
            gap: '0.35rem',
            alignItems: 'center',
            padding: '1rem 1.5rem',
            border: `1px solid ${accent}55`,
            borderRadius: 'var(--pl-radius-full)',
            fontSize: '0.85rem',
            letterSpacing: '0.04em',
          }}
        >
          <span style={{ fontFamily: headingFont, fontSize: '1rem' }}>{coupleLine}</span>
          {(prettyDate || venue) && (
            <span style={{ opacity: 0.75 }}>
              {[prettyDate, venue].filter(Boolean).join(' · ')}
            </span>
          )}
        </div>
      </div>
    </header>
  );
}
