'use client';

/* ========================================================================
   DecorDivider — replaces the flat hairline between sections with a
   hand-drawn editorial flourish generated by GPT Image 2 at library
   time. Renders nothing when manifest.decorLibrary.divider isn't set,
   so existing sites don't grow a wall of images.

   The same URL renders on every divider — we flip it vertically on
   every other instance so the rhythm reads varied, and fade the edges
   so the paper-grain blends into the section below.
   ======================================================================== */

import type { CSSProperties } from 'react';

interface Props {
  url?: string;
  /** Even instances flip vertically so two adjacent dividers don't
   *  read identical. Pass `index` from the block loop. */
  index?: number;
  /** Renders dramatically smaller/softer — used between tighter sections. */
  compact?: boolean;
  style?: CSSProperties;
}

export function DecorDivider({ url, index = 0, compact, style }: Props) {
  if (!url) return null;
  const height = compact ? 56 : 84;
  const flip = index % 2 === 1;

  return (
    <div
      aria-hidden="true"
      className="pl8-decor-divider"
      style={{
        width: '100%',
        height,
        backgroundImage: `url(${url})`,
        backgroundSize: 'auto 100%',
        backgroundRepeat: 'repeat-x',
        backgroundPosition: 'center',
        transform: flip ? 'scaleY(-1)' : undefined,
        maskImage: 'linear-gradient(to right, transparent 0%, black 8%, black 92%, transparent 100%)',
        WebkitMaskImage: 'linear-gradient(to right, transparent 0%, black 8%, black 92%, transparent 100%)',
        opacity: 0.92,
        pointerEvents: 'none',
        ...style,
      }}
    />
  );
}
