'use client';

// ─────────────────────────────────────────────────────────────
// Pearloom / components/landing-page.tsx
// The Loom — Intertwined brand marketing page
// "Pair + Loom" — two lives woven together
// ─────────────────────────────────────────────────────────────

import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Sparkles, Loader2, ArrowRight, Check, Star, Heart } from 'lucide-react';
import { PearloomMark, PearloomWordmark, FloatingThread, WovenCircle } from '@/components/brand/PearloomMark';

interface LandingPageProps {
  handleSignIn: () => void;
  status: 'authenticated' | 'loading' | 'unauthenticated';
}

const FEATURES = [
  { emoji: '🧠', title: 'AI Memory Engine', body: 'Gemini reads your photo metadata, maps your timeline, and writes an intimate narrative — not a template.' },
  { emoji: '📸', title: 'Google Photos Sync', body: 'Select memories directly from your library. No downloading, compressing, or re-uploading.' },
  { emoji: '💌', title: 'RSVP & Guest Manager', body: 'Track RSVPs, meal preferences, song requests, and plus-ones. Every guest accounted for.' },
  { emoji: '🎨', title: 'Magazine-Quality Design', body: 'Cinematic parallax, editorial type hierarchies, and layouts that rival a Condé Nast spread.' },
  { emoji: '🗺', title: 'Travel & Logistics', body: 'Hotels, airports, parking auto-generated by AI and shown publicly for your guests.' },
  { emoji: '✨', title: 'AI Rewrite Anytime', body: 'One click to rewrite any chapter with fresh language. The story stays yours, just more beautiful.' },
];

const TESTIMONIALS = [
  { quote: 'Our guests said it looked like a design studio built it. We did it ourselves in 4 minutes.', name: 'Sarah & James', wedding: 'June 2025 · Napa, CA' },
  { quote: 'The AI described our relationship better than we could have. We both cried reading it.', name: 'Priya & Aiden', wedding: 'March 2026 · Charleston, SC' },
  { quote: "I've built websites professionally for 10 years. I've never seen anything generate this fast and look this good.", name: 'Elena & Marco', wedding: 'September 2025 · Tuscany' },
];

export function LandingPage({ handleSignIn, status }: LandingPageProps) {
  const [activeTestimonial, setActiveTestimonial] = useState(0);
  const [tick, setTick] = useState(0);

  useEffect(() => {
    const t = setInterval(() => setTick(n => n + 1), 4000);
    return () => clearInterval(t);
  }, []);

  useEffect(() => {
    setActiveTestimonial(tick % TESTIMONIALS.length);
  }, [tick]);

  return (
    <div style={{ backgroundColor: '#faf9f6', minHeight: '100vh', fontFamily: 'var(--eg-font-body)', overflowX: 'hidden' }}>

      {/* ══════════════════════════════════════
          HERO — The Loom
      ══════════════════════════════════════ */}
      <section style={{
        minHeight: '100vh',
        display: 'flex', flexDirection: 'column',
        alignItems: 'center', justifyContent: 'center',
        padding: '10rem 2rem 6rem',
        position: 'relative', overflow: 'hidden',
      }}>
        {/* Background floating threads */}
        <FloatingThread x="5%" y="10%" size={80} delay={0} opacity={0.18} />
        <FloatingThread x="88%" y="8%" size={55} delay={1.5} opacity={0.15} />
        <FloatingThread x="78%" y="60%" size={100} delay={3} opacity={0.12} />
        <FloatingThread x="3%" y="65%" size={65} delay={2} opacity={0.14} />
        <FloatingThread x="92%" y="35%" size={45} delay={4} opacity={0.16} />
        <FloatingThread x="15%" y="82%" size={40} delay={1} opacity={0.15} />
        <FloatingThread x="60%" y="88%" size={55} delay={2.5} opacity={0.12} />

        {/* Background warm radial glow */}
        <div style={{
          position: 'absolute', top: '30%', left: '50%', transform: 'translate(-50%,-50%)',
          width: '700px', height: '700px', borderRadius: '50%',
          background: 'radial-gradient(circle, rgba(184,146,106,0.1) 0%, transparent 65%)',
          filter: 'blur(40px)', pointerEvents: 'none',
        }} />

        {/* Subtle woven texture */}
        <div style={{
          position: 'absolute', inset: 0,
          backgroundImage: `
            linear-gradient(45deg, rgba(184,146,106,0.03) 25%, transparent 25%),
            linear-gradient(-45deg, rgba(184,146,106,0.03) 25%, transparent 25%),
            linear-gradient(45deg, transparent 75%, rgba(184,146,106,0.03) 75%),
            linear-gradient(-45deg, transparent 75%, rgba(184,146,106,0.03) 75%)
          `,
          backgroundSize: '20px 20px',
          backgroundPosition: '0 0, 0 10px, 10px -10px, -10px 0px',
          pointerEvents: 'none',
        }} />

        <div style={{ position: 'relative', zIndex: 10, maxWidth: '860px', width: '100%', textAlign: 'center' }}>
          {/* Giant intertwined mark */}
          <motion.div
            initial={{ opacity: 0, scale: 0.8, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            transition={{ duration: 1.2, ease: [0.16, 1, 0.3, 1] }}
            style={{ display: 'flex', justifyContent: 'center', marginBottom: '3rem' }}
          >
            <div style={{ position: 'relative', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}>
              {/* Outer glow rings */}
              {[1, 2, 3].map((ring) => (
                <motion.div
                  key={ring}
                  style={{
                    position: 'absolute',
                    width: 160 + ring * 40, height: 80 + ring * 20,
                    borderRadius: '50%',
                    border: `1px solid rgba(184,146,106,${0.2 - ring * 0.05})`,
                    pointerEvents: 'none',
                  }}
                  animate={{ scale: [1, 1.04, 1] }}
                  transition={{ duration: 4 + ring, repeat: Infinity, ease: 'easeInOut', delay: ring * 0.6 }}
                />
              ))}
              {/* Core logo mark — animated draw-in */}
              <PearloomMark size={160} color="#b8926a" color2="#d4a572" animated />
            </div>
          </motion.div>

          {/* Badge */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.9, ease: [0.16, 1, 0.3, 1], delay: 0.2 }}
            style={{
              display: 'inline-flex', alignItems: 'center', gap: '0.5rem',
              padding: '0.45rem 1.2rem', borderRadius: '2rem',
              background: 'rgba(184,146,106,0.1)', border: '1px solid rgba(184,146,106,0.2)',
              color: '#b8926a', fontSize: '0.72rem', fontWeight: 800,
              letterSpacing: '0.15em', textTransform: 'uppercase',
              marginBottom: '2.5rem',
            }}
          >
            <Sparkles size={11} />
            Powered by Gemini AI · Free to Start
          </motion.div>

          {/* H1 */}
          <motion.h1
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 1.3, delay: 0.3, ease: [0.16, 1, 0.3, 1] }}
            style={{
              fontFamily: 'var(--eg-font-heading)',
              fontSize: 'clamp(4rem, 10.5vw, 8.5rem)',
              fontWeight: 400, lineHeight: 0.92,
              color: '#1a1a1a', letterSpacing: '-0.035em',
              marginBottom: '2.5rem',
            }}
          >
            Your love story,<br />
            <span style={{ fontStyle: 'italic', color: '#b8926a' }}>beautifully&nbsp;woven.</span>
          </motion.h1>

          {/* Sub */}
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 1, delay: 0.5 }}
            style={{
              fontSize: 'clamp(1rem, 2.2vw, 1.2rem)', fontWeight: 300,
              lineHeight: 1.75, color: '#8c8c8c',
              maxWidth: '560px', margin: '0 auto 4rem',
            }}
          >
            Connect Google Photos. Describe your vibe. Pearloom&apos;s AI weaves a
            magazine-quality site for every milestone — in under 90 seconds.
          </motion.p>

          {/* CTA */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.9, delay: 0.65 }}
            style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '1rem' }}
          >
            <button
              onClick={handleSignIn}
              style={{
                display: 'inline-flex', alignItems: 'center', gap: '0.85rem',
                padding: '1.15rem 3.5rem', borderRadius: '100px',
                background: 'linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 100%)',
                color: '#fff', fontSize: '1.05rem', fontWeight: 600,
                border: 'none', cursor: 'pointer', letterSpacing: '0.01em',
                boxShadow: '0 16px 50px rgba(26,26,26,0.22)',
                transition: 'all 0.3s cubic-bezier(0.16,1,0.3,1)',
                fontFamily: 'var(--eg-font-body)',
              }}
              onMouseOver={e => { e.currentTarget.style.transform = 'scale(1.04) translateY(-3px)'; e.currentTarget.style.boxShadow = '0 24px 60px rgba(26,26,26,0.3)'; }}
              onMouseOut={e => { e.currentTarget.style.transform = 'none'; e.currentTarget.style.boxShadow = '0 16px 50px rgba(26,26,26,0.22)'; }}
            >
              {status === 'loading' ? <Loader2 size={20} style={{ animation: 'spin 1s linear infinite' }} /> : <PearloomMark size={24} color="#fff" />}
              Start Building Free
              <ArrowRight size={16} style={{ opacity: 0.6 }} />
            </button>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', fontSize: '0.78rem', color: '#b0b0b0' }}>
              <div style={{ display: 'flex', gap: '0.2rem' }}>
                {[...Array(5)].map((_, i) => <Star key={i} size={11} fill="#b8926a" color="#b8926a" />)}
              </div>
              <span>4.9 rating · No credit card · Free forever</span>
            </div>
          </motion.div>

          {/* Stats pills */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 1, delay: 0.9 }}
            style={{ display: 'flex', gap: '1rem', justifyContent: 'center', marginTop: '5rem', flexWrap: 'wrap' }}
          >
            {[
              { value: '< 90s', label: 'To publish' },
              { value: '10k+', label: 'Couples' },
              { value: '6', label: 'Layouts' },
              { value: '∞', label: 'AI themes' },
            ].map((s) => (
              <div key={s.label} style={{
                padding: '1.25rem 2rem', textAlign: 'center',
                background: 'rgba(255,255,255,0.85)', backdropFilter: 'blur(20px)',
                borderRadius: '1rem',
                border: '1px solid rgba(184,146,106,0.15)',
                boxShadow: '0 8px 30px rgba(0,0,0,0.04)',
                minWidth: '110px',
              }}>
                <div style={{ fontFamily: 'var(--eg-font-heading)', fontSize: '2rem', fontWeight: 400, color: '#1a1a1a', lineHeight: 1 }}>{s.value}</div>
                <div style={{ fontSize: '0.65rem', color: '#b0b0b0', marginTop: '0.4rem', textTransform: 'uppercase', letterSpacing: '0.12em', fontWeight: 700 }}>{s.label}</div>
              </div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* ══════════════════════════════════════
          FEATURES — Card Grid
      ══════════════════════════════════════ */}
      <section style={{ padding: '9rem 2rem', background: '#fff' }}>
        <div style={{ maxWidth: '1200px', margin: '0 auto' }}>
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            style={{ textAlign: 'center', marginBottom: '6rem' }}
          >
            <WovenCircle size={44} style={{ margin: '0 auto 1.5rem' }}>
              <PearloomMark size={24} color="#b8926a" />
            </WovenCircle>
            <h2 style={{
              fontFamily: 'var(--eg-font-heading)',
              fontSize: 'clamp(2.5rem, 5vw, 4rem)',
              fontWeight: 400, color: '#1a1a1a',
              letterSpacing: '-0.025em', lineHeight: 1.05,
              marginTop: '0.5rem',
            }}>
              A complete event platform,<br />
              <span style={{ fontStyle: 'italic', color: '#b8926a' }}>powered by AI</span>
            </h2>
          </motion.div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '1.5rem' }}>
            {FEATURES.map((f, i) => (
              <motion.div
                key={f.title}
                initial={{ opacity: 0, y: 40 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: '-60px' }}
                transition={{ duration: 0.7, delay: i * 0.09 }}
                whileHover={{ y: -8 }}
                style={{
                  background: '#faf9f6', borderRadius: '1.5rem',
                  padding: '2.25rem', border: '1px solid rgba(0,0,0,0.05)',
                  boxShadow: '0 4px 20px rgba(0,0,0,0.03)',
                  cursor: 'default',
                }}
              >
                <WovenCircle size={52} style={{ marginBottom: '1.5rem' }}>
                  <span style={{ fontSize: '1.4rem' }}>{f.emoji}</span>
                </WovenCircle>
                <h3 style={{
                  fontFamily: 'var(--eg-font-heading)', fontSize: '1.35rem',
                  fontWeight: 400, color: '#1a1a1a',
                  marginBottom: '0.75rem', letterSpacing: '-0.01em',
                }}>{f.title}</h3>
                <p style={{ color: '#8c8c8c', fontSize: '0.95rem', lineHeight: 1.8 }}>{f.body}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════
          HOW IT WORKS — Thread spine
      ══════════════════════════════════════ */}
      <section style={{ padding: '9rem 2rem', background: '#faf9f6', position: 'relative' }}>
        {/* Giant background thread outline */}
        <div style={{
          position: 'absolute', top: '50%', right: '-100px', transform: 'translateY(-50%)',
          pointerEvents: 'none', opacity: 0.08,
        }}>
          <PearloomMark size={500} color="#b8926a" />
        </div>

        <div style={{ maxWidth: '820px', margin: '0 auto' }}>
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            style={{ textAlign: 'center', marginBottom: '6rem' }}
          >
            <h2 style={{
              fontFamily: 'var(--eg-font-heading)',
              fontSize: 'clamp(2.5rem, 5vw, 4rem)',
              fontWeight: 400, color: '#1a1a1a',
              letterSpacing: '-0.025em', lineHeight: 1.05,
            }}>
              From photos to published<br />
              <span style={{ fontStyle: 'italic', color: '#b8926a' }}>in 3 steps</span>
            </h2>
          </motion.div>

          <div style={{ position: 'relative' }}>
            {/* Vertical connecting line — woven double-line */}
            <div style={{
              position: 'absolute', left: '2.35rem', top: '3rem', bottom: '3rem',
              width: '3px', display: 'flex', flexDirection: 'column',
            }}>
              <div style={{ flex: 1, background: 'linear-gradient(to bottom, rgba(184,146,106,0.35), rgba(184,146,106,0.05))', width: '1px', marginLeft: '0px' }} />
              <div style={{ position: 'absolute', inset: 0, width: '1px', marginLeft: '2px', background: 'linear-gradient(to bottom, rgba(184,146,106,0.2), rgba(184,146,106,0.03))' }} />
            </div>

            {[
              { emoji: '📸', step: '01', title: 'Connect your photos', body: 'Link Google Photos or upload directly. Up to 30 memories per site.' },
              { emoji: '✍️', step: '02', title: 'Describe your story', body: 'Tell us your vibe, occasion, and aesthetic. Our wizard turns words into a rich AI prompt.' },
              { emoji: '🚀', step: '03', title: 'Publish in one click', body: 'Your stunning site is live at yourname.pearloom.app in under 90 seconds.' },
            ].map((item, i) => (
              <motion.div
                key={item.step}
                initial={{ opacity: 0, x: -30 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true, margin: '-60px' }}
                transition={{ duration: 0.8, delay: i * 0.15 }}
                style={{ display: 'flex', gap: '2.5rem', alignItems: 'flex-start', marginBottom: '4rem' }}
              >
                <WovenCircle
                  size={48}
                  color={i === 0 ? 'linear-gradient(160deg, #e8cba8, #d4a572)' : 'rgba(184,146,106,0.1)'}
                  borderColor="rgba(184,146,106,0.3)"
                  style={{
                    background: i === 0 ? 'linear-gradient(160deg, #e8cba8, #d4a572)' : 'rgba(184,146,106,0.08)',
                    boxShadow: i === 0 ? '0 8px 24px rgba(184,146,106,0.3)' : 'none',
                  }}
                >
                  <span style={{ fontSize: '1.3rem' }}>{item.emoji}</span>
                </WovenCircle>

                <div style={{ paddingTop: '0.5rem' }}>
                  <div style={{ fontSize: '0.68rem', fontWeight: 800, letterSpacing: '0.22em', color: '#b8926a', textTransform: 'uppercase', marginBottom: '0.5rem' }}>
                    Step {item.step}
                  </div>
                  <h3 style={{
                    fontFamily: 'var(--eg-font-heading)', fontSize: '2rem',
                    fontWeight: 400, color: '#1a1a1a',
                    letterSpacing: '-0.015em', marginBottom: '0.75rem',
                  }}>
                    {item.title}
                  </h3>
                  <p style={{ color: '#8c8c8c', lineHeight: 1.8, fontSize: '1rem', maxWidth: '480px' }}>{item.body}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════
          TESTIMONIALS — Dark Section
      ══════════════════════════════════════ */}
      <section style={{ padding: '9rem 2rem', background: '#1a1a1a', position: 'relative', overflow: 'hidden' }}>
        {/* Giant background thread outlines */}
        <div style={{
          position: 'absolute', left: '-60px', top: '50%', transform: 'translateY(-50%)',
          pointerEvents: 'none', opacity: 0.06,
        }}>
          <PearloomMark size={400} color="#b8926a" />
        </div>
        <div style={{
          position: 'absolute', right: '-40px', bottom: '-20px',
          pointerEvents: 'none', opacity: 0.04,
        }}>
          <PearloomMark size={300} color="#b8926a" />
        </div>

        <div style={{ maxWidth: '800px', margin: '0 auto', textAlign: 'center', position: 'relative', zIndex: 1 }}>
          <WovenCircle size={44} color="rgba(184,146,106,0.1)" borderColor="rgba(184,146,106,0.3)" style={{ margin: '0 auto 2rem' }}>
            <span style={{ fontSize: '1.1rem' }}>💬</span>
          </WovenCircle>
          <h2 style={{
            fontFamily: 'var(--eg-font-heading)',
            fontSize: 'clamp(2.5rem, 5vw, 4rem)',
            fontWeight: 400, color: '#fff',
            letterSpacing: '-0.025em', lineHeight: 1.05,
            marginBottom: '5rem',
          }}>
            Couples who trusted<br />
            <span style={{ fontStyle: 'italic', color: '#b8926a' }}>Pearloom</span>
          </h2>

          {/* Carousel */}
          <div style={{ position: 'relative', minHeight: '200px' }}>
            <AnimatePresence mode="wait">
              <motion.div
                key={activeTestimonial}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -20 }}
                transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
                style={{
                  background: 'rgba(255,255,255,0.04)',
                  borderRadius: '2rem', padding: '3rem',
                  border: '1px solid rgba(255,255,255,0.08)',
                }}
              >
                <div style={{ display: 'flex', gap: '0.25rem', justifyContent: 'center', marginBottom: '2rem' }}>
                  {[...Array(5)].map((_, j) => <Star key={j} size={16} fill="#b8926a" color="#b8926a" />)}
                </div>
                <p style={{
                  fontFamily: 'var(--eg-font-heading)', fontSize: 'clamp(1.2rem, 2.5vw, 1.6rem)',
                  fontWeight: 400, fontStyle: 'italic',
                  color: 'rgba(255,255,255,0.9)', lineHeight: 1.6, marginBottom: '2.5rem',
                }}>
                  &ldquo;{TESTIMONIALS[activeTestimonial].quote}&rdquo;
                </p>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '1rem' }}>
                  <WovenCircle
                    size={44}
                    color="linear-gradient(135deg, #b8926a, #8b6b4a)"
                    borderColor="rgba(184,146,106,0.3)"
                    style={{ background: 'linear-gradient(135deg, #b8926a, #8b6b4a)' }}
                  >
                    <span style={{ color: '#fff', fontWeight: 700, fontSize: '1rem' }}>
                      {TESTIMONIALS[activeTestimonial].name[0]}
                    </span>
                  </WovenCircle>
                  <div style={{ textAlign: 'left' }}>
                    <div style={{ fontWeight: 700, color: '#fff', fontSize: '0.9rem' }}>{TESTIMONIALS[activeTestimonial].name}</div>
                    <div style={{ fontSize: '0.75rem', color: 'rgba(255,255,255,0.4)', marginTop: '0.1rem' }}>{TESTIMONIALS[activeTestimonial].wedding}</div>
                  </div>
                </div>
              </motion.div>
            </AnimatePresence>
          </div>

          {/* Dots */}
          <div style={{ display: 'flex', gap: '0.5rem', justifyContent: 'center', marginTop: '2rem' }}>
            {TESTIMONIALS.map((_, i) => (
              <button
                key={i}
                onClick={() => setActiveTestimonial(i)}
                style={{
                  width: i === activeTestimonial ? '24px' : '8px',
                  height: '8px', borderRadius: '999px',
                  background: i === activeTestimonial ? '#b8926a' : 'rgba(255,255,255,0.2)',
                  border: 'none', cursor: 'pointer',
                  transition: 'all 0.3s ease',
                }}
              />
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════
          PRICING — All Included
      ══════════════════════════════════════ */}
      <section style={{ padding: '9rem 2rem', background: '#faf9f6' }}>
        <div style={{ maxWidth: '680px', margin: '0 auto' }}>
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            style={{ textAlign: 'center', marginBottom: '4rem' }}
          >
            <h2 style={{
              fontFamily: 'var(--eg-font-heading)',
              fontSize: 'clamp(2.5rem, 5vw, 4rem)',
              fontWeight: 400, color: '#1a1a1a',
              letterSpacing: '-0.025em', lineHeight: 1.05,
            }}>
              Start free.<br />
              <span style={{ fontStyle: 'italic', color: '#b8926a' }}>Stay beautiful.</span>
            </h2>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            style={{
              background: '#fff', borderRadius: '2rem',
              border: '1px solid rgba(0,0,0,0.06)',
              boxShadow: '0 12px 50px rgba(0,0,0,0.05)',
              overflow: 'hidden',
            }}
          >
            {/* Header stripe */}
            <div style={{
              background: 'linear-gradient(135deg, #1a1a1a, #2d2d2d)',
              padding: '2.5rem 3rem',
              display: 'flex', alignItems: 'center', gap: '1.5rem',
            }}>
              <WovenCircle size={52} color="rgba(184,146,106,0.15)" borderColor="rgba(184,146,106,0.4)" style={{ flexShrink: 0 }}>
                <PearloomMark size={28} color="#b8926a" />
              </WovenCircle>
              <div>
                <div style={{ color: '#fff', fontFamily: 'var(--eg-font-heading)', fontSize: '1.75rem', fontWeight: 400, letterSpacing: '-0.01em' }}>Free Forever</div>
                <div style={{ color: 'rgba(255,255,255,0.45)', fontSize: '0.85rem', marginTop: '0.2rem' }}>No credit card required · No hidden fees</div>
              </div>
              <div style={{ marginLeft: 'auto', textAlign: 'right' }}>
                <div style={{ fontFamily: 'var(--eg-font-heading)', fontSize: '3rem', fontWeight: 400, color: '#fff', lineHeight: 1 }}>$0</div>
                <div style={{ fontSize: '0.72rem', color: 'rgba(255,255,255,0.3)', letterSpacing: '0.1em' }}>FOREVER</div>
              </div>
            </div>

            {/* Feature list */}
            <div style={{ padding: '2rem 3rem' }}>
              {[
                'AI-generated story chapters from your photos',
                'Event cards, RSVP & guest manager',
                'Registry showcase & travel logistics',
                'Social OG preview card for sharing',
                'Drag-and-drop editor with AI rewrite',
                'Live countdown to your special day',
                'Published at yourname.pearloom.app',
                'FAQ accordion for guests',
              ].map((feat) => (
                <div key={feat} style={{
                  display: 'flex', alignItems: 'center', gap: '1rem',
                  padding: '0.875rem 0',
                  borderBottom: '1px solid rgba(0,0,0,0.04)',
                }}>
                  <WovenCircle size={22} style={{ flexShrink: 0 }}>
                    <Check size={11} color="#b8926a" strokeWidth={2.5} />
                  </WovenCircle>
                  <span style={{ fontSize: '0.95rem', color: '#3a3a3a' }}>{feat}</span>
                </div>
              ))}

              <button
                onClick={handleSignIn}
                style={{
                  width: '100%', marginTop: '2rem',
                  padding: '1.15rem', borderRadius: '100px',
                  background: 'linear-gradient(135deg, #b8926a, #8b6b4a)',
                  color: '#fff', fontSize: '1rem', fontWeight: 700,
                  border: 'none', cursor: 'pointer',
                  boxShadow: '0 12px 40px rgba(184,146,106,0.4)',
                  fontFamily: 'var(--eg-font-body)', letterSpacing: '0.01em',
                  display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.75rem',
                }}
                onMouseOver={e => { e.currentTarget.style.transform = 'translateY(-2px)'; }}
                onMouseOut={e => { e.currentTarget.style.transform = 'none'; }}
              >
                <Heart size={18} />
                Start Building Free
                <ArrowRight size={16} style={{ opacity: 0.7 }} />
              </button>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ══════════════════════════════════════
          FOOTER — Elegant Close
      ══════════════════════════════════════ */}
      <footer style={{ background: '#1a1a1a', padding: '8rem 2rem 5rem', textAlign: 'center', position: 'relative', overflow: 'hidden' }}>
        {/* Large thread outline center */}
        <div style={{
          position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%,-50%)',
          pointerEvents: 'none', opacity: 0.05,
        }}>
          <PearloomMark size={500} color="#b8926a" />
        </div>

        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          style={{ maxWidth: '600px', margin: '0 auto', position: 'relative', zIndex: 1 }}
        >
          <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '3rem' }}>
            <PearloomMark size={80} color="#b8926a" color2="rgba(184,146,106,0.5)" />
          </div>
          <h2 style={{
            fontFamily: 'var(--eg-font-heading)',
            fontSize: 'clamp(2.5rem, 5vw, 4.5rem)',
            fontWeight: 400, color: '#fff',
            letterSpacing: '-0.03em', lineHeight: 1.05,
            marginBottom: '1.5rem',
          }}>
            Ready to weave<br />
            <span style={{ fontStyle: 'italic', color: '#b8926a' }}>your love story?</span>
          </h2>
          <p style={{ color: 'rgba(255,255,255,0.4)', fontSize: '1rem', lineHeight: 1.65, marginBottom: '4rem' }}>
            Thousands of couples building beautiful sites for every milestone.
          </p>

          <button
            onClick={handleSignIn}
            style={{
              display: 'inline-flex', alignItems: 'center', gap: '0.75rem',
              padding: '1.15rem 3.5rem', borderRadius: '100px',
              background: 'linear-gradient(135deg, #b8926a, #8b6b4a)',
              color: '#fff', fontSize: '1.05rem', fontWeight: 600,
              border: 'none', cursor: 'pointer',
              boxShadow: '0 14px 50px rgba(184,146,106,0.4)',
              fontFamily: 'var(--eg-font-body)',
            }}
            onMouseOver={e => { e.currentTarget.style.transform = 'scale(1.04) translateY(-3px)'; }}
            onMouseOut={e => { e.currentTarget.style.transform = 'none'; }}
          >
            <PearloomMark size={22} color="#fff" />
            Start Building Free
          </button>

          <div style={{ marginTop: '4rem', display: 'flex', justifyContent: 'center', gap: '2rem', flexWrap: 'wrap' }}>
            {['© 2026 Pearloom', 'Built by Pixel Boba Studio', 'Privacy', 'Terms'].map((item) => (
              <span key={item} style={{ fontSize: '0.72rem', color: 'rgba(255,255,255,0.18)', letterSpacing: '0.08em' }}>{item}</span>
            ))}
          </div>
        </motion.div>
      </footer>
    </div>
  );
}
