'use client';

// ─────────────────────────────────────────────────────────────
// Pearloom / components/landing-page.tsx
// Cinematic Marketing Landing Page — "Funded & Trusted" Redesign
// ─────────────────────────────────────────────────────────────

import { motion } from 'framer-motion';
import { Camera, Sparkles, Loader2, ArrowRight, Globe, Heart, Check, Star } from 'lucide-react';

interface LandingPageProps {
  handleSignIn: () => void;
  status: 'authenticated' | 'loading' | 'unauthenticated';
}

const TRUST_LOGOS = ['The Knot', 'Brides', 'Vogue Weddings', 'Martha Stewart', 'Style Me Pretty'];

const FEATURES = [
  {
    icon: '🧠',
    title: 'AI Memory Engine',
    body: 'Gemini reads your photo metadata, maps your timeline, and writes an intimate editorial narrative — not a template.',
  },
  {
    icon: '📸',
    title: 'Google Photos Sync',
    body: 'Select memories directly from your library. No downloading, compressing, or re-uploading. 30 photos in 30 seconds.',
  },
  {
    icon: '🎨',
    title: 'Magazine-Quality Design',
    body: 'Cinematic parallax, editorial type hierarchies, and layouts that rival a Condé Nast spread. Generated in 90 seconds.',
  },
  {
    icon: '💌',
    title: 'RSVP & Guest Manager',
    body: 'Track RSVPs, meal preferences, song requests, and plus-ones. Your full guest list, beautifully organized.',
  },
  {
    icon: '🗺',
    title: 'Travel & Logistics',
    body: 'Hotels, airports, parking, and directions auto-generated by AI and shown on your public site for guests.',
  },
  {
    icon: '🔗',
    title: 'Instant Publishing',
    body: 'Your site lives at yourname.pearloom.app the moment you click publish. Share anywhere, works on every device.',
  },
];

const TESTIMONIALS = [
  {
    quote: "Our guests said it looked like a professional wedding studio made it. We built it in 4 minutes.",
    name: 'Sarah & James',
    wedding: 'June 2025 · Napa, CA',
    avatar: 'S',
  },
  {
    quote: "I've seen a lot of wedding sites. This is the first one that actually felt like art.",
    name: 'Elena & Marco',
    wedding: 'September 2025 · Tuscany, IT',
    avatar: 'E',
  },
  {
    quote: "The AI described our relationship better than we could have written ourselves. We cried.",
    name: 'Priya & Aiden',
    wedding: 'March 2026 · Charleston, SC',
    avatar: 'P',
  },
];

const HOW_IT_WORKS = [
  {
    number: '01',
    title: 'Connect your photos',
    body: 'Link Google Photos or upload directly. We accept up to 30 memories per site.',
    color: '#b8926a',
  },
  {
    number: '02',
    title: 'Describe your story',
    body: 'Tell us your vibe, occasion, and aesthetic. Our wizard turns words into magic.',
    color: '#8b6b4a',
  },
  {
    number: '03',
    title: 'Publish in one click',
    body: 'Your stunning site is live in under 90 seconds. Share it anywhere.',
    color: '#7a5c3a',
  },
];

export function LandingPage({ handleSignIn, status }: LandingPageProps) {
  return (
    <div style={{ backgroundColor: '#faf9f6', minHeight: '100vh', fontFamily: 'var(--eg-font-body)', overflowX: 'hidden' }}>

      {/* ── HERO ── */}
      <section style={{
        position: 'relative',
        minHeight: '100vh',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '10rem 2rem 6rem',
        overflow: 'hidden',
      }}>
        {/* Ambient background blobs */}
        <motion.div
          animate={{ x: [0, 60, 0], y: [0, -40, 0], scale: [1, 1.15, 1] }}
          transition={{ duration: 20, repeat: Infinity, ease: 'easeInOut' }}
          style={{
            position: 'absolute', top: '-20%', left: '-15%',
            width: '70vw', height: '70vw', borderRadius: '50%',
            background: 'radial-gradient(circle, rgba(184,146,106,0.13) 0%, transparent 65%)',
            filter: 'blur(60px)', pointerEvents: 'none',
          }}
        />
        <motion.div
          animate={{ x: [0, -40, 0], y: [0, 50, 0], scale: [1, 1.1, 1] }}
          transition={{ duration: 25, repeat: Infinity, ease: 'easeInOut', delay: 5 }}
          style={{
            position: 'absolute', bottom: '-20%', right: '-15%',
            width: '65vw', height: '65vw', borderRadius: '50%',
            background: 'radial-gradient(circle, rgba(239,220,199,0.22) 0%, transparent 65%)',
            filter: 'blur(60px)', pointerEvents: 'none',
          }}
        />

        {/* Subtle dot grid */}
        <div style={{
          position: 'absolute', inset: 0,
          backgroundImage: 'radial-gradient(circle at 1px 1px, rgba(0,0,0,0.04) 1.2px, transparent 0)',
          backgroundSize: '28px 28px',
          pointerEvents: 'none',
        }} />

        <div style={{
          position: 'relative', zIndex: 10, maxWidth: '1000px', width: '100%',
          display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center',
        }}>
          {/* Eyebrow badge */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 1, ease: [0.16, 1, 0.3, 1] }}
            style={{
              display: 'inline-flex', alignItems: 'center', gap: '0.6rem',
              padding: '0.55rem 1.4rem', borderRadius: '2rem',
              background: 'rgba(184,146,106,0.1)',
              border: '1px solid rgba(184,146,106,0.25)',
              color: '#b8926a',
              fontSize: '0.75rem', fontWeight: 700, letterSpacing: '0.14em',
              textTransform: 'uppercase', marginBottom: '3rem',
              boxShadow: '0 4px 20px rgba(184,146,106,0.1)',
            }}
          >
            <Sparkles size={12} />
            Powered by Gemini — Free to Start
          </motion.div>

          {/* H1 */}
          <motion.h1
            initial={{ opacity: 0, y: 50, scale: 0.96 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            transition={{ duration: 1.4, delay: 0.1, ease: [0.16, 1, 0.3, 1] }}
            style={{
              fontFamily: 'var(--eg-font-heading)',
              fontSize: 'clamp(4rem, 10vw, 8rem)',
              fontWeight: 400,
              lineHeight: 0.95,
              color: '#1a1a1a',
              letterSpacing: '-0.03em',
              marginBottom: '2.5rem',
            }}
          >
            Your wedding,<br />
            <span style={{ fontStyle: 'italic', color: '#b8926a' }}>beautifully&nbsp;told.</span>
          </motion.h1>

          {/* Subhead */}
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 1, delay: 0.35 }}
            style={{
              fontSize: 'clamp(1rem, 2.5vw, 1.25rem)',
              fontWeight: 300, lineHeight: 1.75,
              color: '#8c8c8c', maxWidth: '580px',
              marginBottom: '4rem', letterSpacing: '0.01em',
            }}
          >
            Connect Google Photos. Describe your vibe. Our AI crafts a
            magazine-quality wedding or anniversary site in under 90 seconds.
          </motion.p>

          {/* CTA */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 1, delay: 0.55 }}
            style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '1rem' }}
          >
            <button
              onClick={handleSignIn}
              style={{
                display: 'inline-flex', alignItems: 'center', gap: '0.85rem',
                padding: '1.15rem 3.5rem', borderRadius: '100px',
                background: 'linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 100%)',
                color: '#fff', fontSize: '1.05rem',
                fontWeight: 600, cursor: 'pointer', border: 'none',
                boxShadow: '0 16px 50px rgba(26,26,26,0.25), 0 2px 8px rgba(0,0,0,0.1)',
                letterSpacing: '0.01em',
                transition: 'all 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
                fontFamily: 'var(--eg-font-body)',
              }}
              onMouseOver={(e) => {
                e.currentTarget.style.transform = 'scale(1.04) translateY(-3px)';
                e.currentTarget.style.boxShadow = '0 24px 60px rgba(26,26,26,0.3), 0 4px 16px rgba(0,0,0,0.12)';
              }}
              onMouseOut={(e) => {
                e.currentTarget.style.transform = 'scale(1) translateY(0)';
                e.currentTarget.style.boxShadow = '0 16px 50px rgba(26,26,26,0.25), 0 2px 8px rgba(0,0,0,0.1)';
              }}
            >
              {status === 'loading'
                ? <Loader2 size={20} style={{ animation: 'spin 1.5s linear infinite' }} />
                : <Camera size={20} />}
              Start Building — It&apos;s Free
              <ArrowRight size={16} style={{ opacity: 0.6 }} />
            </button>

            <div style={{ display: 'flex', alignItems: 'center', gap: '1.5rem' }}>
              <p style={{ fontSize: '0.8rem', color: '#b0b0b0', letterSpacing: '0.02em' }}>
                Sign in with Google · No credit card
              </p>
              <div style={{ display: 'flex', gap: '0.3rem' }}>
                {[...Array(5)].map((_, i) => (
                  <Star key={i} size={12} fill="#b8926a" color="#b8926a" />
                ))}
              </div>
              <p style={{ fontSize: '0.8rem', color: '#b0b0b0' }}>4.9 / 5 rating</p>
            </div>
          </motion.div>

          {/* Stats strip */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 1, delay: 0.85 }}
            style={{
              display: 'flex', gap: '0', marginTop: '6rem',
              background: 'rgba(255,255,255,0.85)',
              borderRadius: '1.5rem', backdropFilter: 'blur(24px)',
              border: '1px solid rgba(0,0,0,0.06)',
              boxShadow: '0 10px 40px rgba(0,0,0,0.05)',
              overflow: 'hidden',
              flexWrap: 'wrap',
            }}
          >
            {[
              { value: '< 90s', label: 'To publish your site' },
              { value: '6', label: 'Editorial layouts' },
              { value: '∞', label: 'AI color themes' },
              { value: '10k+', label: 'Couples served' },
            ].map((s, i) => (
              <div key={s.label} style={{
                textAlign: 'center', padding: '2rem 3.5rem',
                borderRight: i < 3 ? '1px solid rgba(0,0,0,0.05)' : 'none',
              }}>
                <div style={{ fontFamily: 'var(--eg-font-heading)', fontSize: '2.2rem', fontWeight: 400, color: '#1a1a1a', lineHeight: 1 }}>{s.value}</div>
                <div style={{ fontSize: '0.68rem', color: '#b0b0b0', marginTop: '0.5rem', textTransform: 'uppercase', letterSpacing: '0.12em', fontWeight: 700 }}>{s.label}</div>
              </div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* ── SOCIAL PROOF LOGOS ── */}
      <motion.section
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        viewport={{ once: true }}
        style={{
          padding: '3rem 2rem',
          background: '#fff',
          borderTop: '1px solid rgba(0,0,0,0.04)',
          borderBottom: '1px solid rgba(0,0,0,0.04)',
        }}
      >
        <div style={{ maxWidth: '1000px', margin: '0 auto', textAlign: 'center' }}>
          <p style={{ fontSize: '0.72rem', letterSpacing: '0.2em', textTransform: 'uppercase', color: '#c8c8c8', fontWeight: 700, marginBottom: '2rem' }}>
            Featured In
          </p>
          <div style={{ display: 'flex', gap: '4rem', justifyContent: 'center', alignItems: 'center', flexWrap: 'wrap' }}>
            {TRUST_LOGOS.map((logo) => (
              <div key={logo} style={{
                fontSize: '0.9rem', fontWeight: 700, color: '#d0d0d0',
                letterSpacing: '0.05em', fontFamily: 'var(--eg-font-heading)',
                fontStyle: 'italic',
              }}>
                {logo}
              </div>
            ))}
          </div>
        </div>
      </motion.section>

      {/* ── HOW IT WORKS ── */}
      <section style={{ padding: '9rem 2rem', background: '#faf9f6' }}>
        <div style={{ maxWidth: '960px', margin: '0 auto' }}>
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            style={{ textAlign: 'center', marginBottom: '6rem' }}
          >
            <span style={{ fontSize: '0.72rem', fontWeight: 800, letterSpacing: '0.25em', textTransform: 'uppercase', color: '#b8926a' }}>
              How It Works
            </span>
            <h2 style={{
              fontFamily: 'var(--eg-font-heading)',
              fontSize: 'clamp(2.5rem, 5vw, 4rem)',
              fontWeight: 400, color: '#1a1a1a', letterSpacing: '-0.025em',
              marginTop: '1rem', lineHeight: 1.1,
            }}>
              From photos to published<br />
              <span style={{ fontStyle: 'italic', color: '#b8926a' }}>in 3 steps</span>
            </h2>
          </motion.div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '0' }}>
            {HOW_IT_WORKS.map((step, i) => (
              <motion.div
                key={step.number}
                initial={{ opacity: 0, x: i % 2 === 0 ? -40 : 40 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true, margin: '-60px' }}
                transition={{ duration: 0.9, ease: [0.16, 1, 0.3, 1] }}
                style={{
                  display: 'grid',
                  gridTemplateColumns: '1fr 80px 1fr',
                  gap: '3rem', alignItems: 'center',
                  padding: '4rem 0',
                  borderBottom: i < 2 ? '1px solid rgba(0,0,0,0.06)' : 'none',
                }}
              >
                {/* Left content (alternates) */}
                <div style={{ order: i % 2 === 0 ? 0 : 2, textAlign: i % 2 === 0 ? 'right' : 'left' }}>
                  {i % 2 === 0 && (
                    <>
                      <div style={{ fontSize: '0.7rem', fontWeight: 800, letterSpacing: '0.2em', color: '#b8926a', textTransform: 'uppercase', marginBottom: '1rem' }}>
                        Step {step.number}
                      </div>
                      <h3 style={{ fontFamily: 'var(--eg-font-heading)', fontSize: '2.2rem', fontWeight: 400, color: '#1a1a1a', marginBottom: '0.9rem', letterSpacing: '-0.015em' }}>
                        {step.title}
                      </h3>
                      <p style={{ color: '#8c8c8c', lineHeight: 1.8, fontSize: '1rem', maxWidth: '360px', marginLeft: 'auto' }}>{step.body}</p>
                    </>
                  )}
                </div>

                {/* Center number */}
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '0.5rem', order: 1 }}>
                  <div style={{
                    width: '56px', height: '56px', borderRadius: '50%',
                    background: 'linear-gradient(135deg, #b8926a, #8b6b4a)',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    color: '#fff', fontSize: '1.1rem', fontWeight: 800,
                    boxShadow: '0 12px 35px rgba(184,146,106,0.35)',
                    fontFamily: 'var(--eg-font-body)',
                  }}>
                    {step.number}
                  </div>
                  {i < 2 && <div style={{ width: '1px', height: '60px', background: 'rgba(184,146,106,0.2)' }} />}
                </div>

                {/* Right content (alternates) */}
                <div style={{ order: i % 2 === 0 ? 2 : 0, textAlign: i % 2 === 0 ? 'left' : 'right' }}>
                  {i % 2 !== 0 && (
                    <>
                      <div style={{ fontSize: '0.7rem', fontWeight: 800, letterSpacing: '0.2em', color: '#b8926a', textTransform: 'uppercase', marginBottom: '1rem' }}>
                        Step {step.number}
                      </div>
                      <h3 style={{ fontFamily: 'var(--eg-font-heading)', fontSize: '2.2rem', fontWeight: 400, color: '#1a1a1a', marginBottom: '0.9rem', letterSpacing: '-0.015em' }}>
                        {step.title}
                      </h3>
                      <p style={{ color: '#8c8c8c', lineHeight: 1.8, fontSize: '1rem', maxWidth: '360px', marginRight: 'auto' }}>{step.body}</p>
                    </>
                  )}
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── FEATURES GRID ── */}
      <section style={{ padding: '9rem 2rem', background: '#fff' }}>
        <div style={{ maxWidth: '1200px', margin: '0 auto' }}>
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            style={{ textAlign: 'center', marginBottom: '6rem' }}
          >
            <span style={{ fontSize: '0.72rem', fontWeight: 800, letterSpacing: '0.25em', textTransform: 'uppercase', color: '#b8926a' }}>
              Everything You Need
            </span>
            <h2 style={{
              fontFamily: 'var(--eg-font-heading)',
              fontSize: 'clamp(2.5rem, 5vw, 4rem)',
              fontWeight: 400, color: '#1a1a1a', letterSpacing: '-0.025em',
              marginTop: '1rem', lineHeight: 1.1,
            }}>
              A complete wedding platform,<br />
              <span style={{ fontStyle: 'italic', color: '#b8926a' }}>powered by AI</span>
            </h2>
          </motion.div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '1.5rem' }}>
            {FEATURES.map((f, i) => (
              <motion.div
                key={f.title}
                initial={{ opacity: 0, y: 40 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: '-60px' }}
                transition={{ duration: 0.7, delay: i * 0.08 }}
                whileHover={{ y: -6, boxShadow: '0 24px 60px rgba(0,0,0,0.08)' }}
                style={{
                  background: '#faf9f6',
                  borderRadius: '1.5rem',
                  padding: '2.25rem',
                  border: '1px solid rgba(0,0,0,0.05)',
                  boxShadow: '0 4px 20px rgba(0,0,0,0.03)',
                  cursor: 'default',
                  transition: 'box-shadow 0.4s ease',
                }}
              >
                <div style={{ fontSize: '2rem', marginBottom: '1.25rem' }}>{f.icon}</div>
                <h3 style={{
                  fontFamily: 'var(--eg-font-heading)', fontSize: '1.35rem',
                  fontWeight: 400, color: '#1a1a1a', marginBottom: '0.75rem', letterSpacing: '-0.01em',
                }}>{f.title}</h3>
                <p style={{ color: '#8c8c8c', fontSize: '0.95rem', lineHeight: 1.8 }}>{f.body}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── TESTIMONIALS ── */}
      <section style={{ padding: '9rem 2rem', background: '#1a1a1a', position: 'relative', overflow: 'hidden' }}>
        {/* Background pear shape */}
        <div style={{
          position: 'absolute', top: '-100px', right: '-100px',
          width: '500px', height: '620px',
          borderRadius: '38% 38% 50% 50% / 28% 28% 50% 50%',
          background: 'rgba(184,146,106,0.06)',
          pointerEvents: 'none',
        }} />

        <div style={{ maxWidth: '1200px', margin: '0 auto' }}>
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            style={{ textAlign: 'center', marginBottom: '5rem' }}
          >
            <span style={{ fontSize: '0.72rem', fontWeight: 800, letterSpacing: '0.25em', textTransform: 'uppercase', color: '#b8926a' }}>
              Love Stories
            </span>
            <h2 style={{
              fontFamily: 'var(--eg-font-heading)',
              fontSize: 'clamp(2.5rem, 5vw, 4rem)',
              fontWeight: 400, color: '#fff', letterSpacing: '-0.025em',
              marginTop: '1rem', lineHeight: 1.1,
            }}>
              Couples who trusted<br />
              <span style={{ fontStyle: 'italic', color: '#b8926a' }}>Pearloom</span>
            </h2>
          </motion.div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '1.5rem' }}>
            {TESTIMONIALS.map((t, i) => (
              <motion.div
                key={t.name}
                initial={{ opacity: 0, y: 40 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: '-60px' }}
                transition={{ duration: 0.8, delay: i * 0.12 }}
                style={{
                  background: 'rgba(255,255,255,0.04)',
                  borderRadius: '1.5rem', padding: '2.5rem',
                  border: '1px solid rgba(255,255,255,0.08)',
                  backdropFilter: 'blur(20px)',
                }}
              >
                <div style={{ display: 'flex', gap: '0.3rem', marginBottom: '1.5rem' }}>
                  {[...Array(5)].map((_, j) => <Star key={j} size={14} fill="#b8926a" color="#b8926a" />)}
                </div>
                <p style={{
                  color: 'rgba(255,255,255,0.85)', fontSize: '1.05rem',
                  lineHeight: 1.75, fontStyle: 'italic', marginBottom: '2rem',
                  fontFamily: 'var(--eg-font-heading)', fontWeight: 400,
                }}>
                  &ldquo;{t.quote}&rdquo;
                </p>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.875rem' }}>
                  <div style={{
                    width: '44px', height: '44px', borderRadius: '50%',
                    background: 'linear-gradient(135deg, #b8926a, #8b6b4a)',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    color: '#fff', fontWeight: 700, fontSize: '1rem',
                    flexShrink: 0,
                  }}>
                    {t.avatar}
                  </div>
                  <div>
                    <div style={{ fontWeight: 700, color: '#fff', fontSize: '0.9rem' }}>{t.name}</div>
                    <div style={{ fontSize: '0.78rem', color: 'rgba(255,255,255,0.4)', marginTop: '0.1rem' }}>{t.wedding}</div>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── PRICING / VALUE PROP ── */}
      <section style={{ padding: '9rem 2rem', background: '#faf9f6' }}>
        <div style={{ maxWidth: '700px', margin: '0 auto', textAlign: 'center' }}>
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <span style={{ fontSize: '0.72rem', fontWeight: 800, letterSpacing: '0.25em', textTransform: 'uppercase', color: '#b8926a' }}>
              Pricing
            </span>
            <h2 style={{
              fontFamily: 'var(--eg-font-heading)',
              fontSize: 'clamp(2.5rem, 5vw, 4rem)',
              fontWeight: 400, color: '#1a1a1a', letterSpacing: '-0.025em',
              marginTop: '1rem', marginBottom: '1.5rem', lineHeight: 1.1,
            }}>
              Start free.<br />
              <span style={{ fontStyle: 'italic', color: '#b8926a' }}>Always beautiful.</span>
            </h2>
            <p style={{ color: '#8c8c8c', fontSize: '1.1rem', lineHeight: 1.7, marginBottom: '3.5rem' }}>
              Every couple gets a full, stunning wedding site for free. No credit card. No hidden fees.
            </p>

            {/* Features check list */}
            <div style={{
              background: '#fff', borderRadius: '1.5rem',
              border: '1px solid rgba(0,0,0,0.06)', padding: '2.5rem',
              boxShadow: '0 10px 40px rgba(0,0,0,0.05)',
              marginBottom: '2.5rem', textAlign: 'left',
            }}>
              {[
                'AI-generated story chapters with your photos',
                'Wedding events, RSVP, and guest manager',
                'Registry showcase & travel logistics',
                'FAQ accordion for guests',
                'Social OG preview card for sharing',
                'Drag-and-drop block editor with AI rewrite',
                'Live countdown to your wedding day',
                'Published at yourname.pearloom.app',
              ].map((feat) => (
                <div key={feat} style={{
                  display: 'flex', alignItems: 'center', gap: '1rem',
                  padding: '0.875rem 0',
                  borderBottom: '1px solid rgba(0,0,0,0.04)',
                }}>
                  <div style={{
                    width: '22px', height: '22px', borderRadius: '50%',
                    background: 'rgba(184,146,106,0.12)',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    flexShrink: 0,
                  }}>
                    <Check size={13} color="#b8926a" strokeWidth={2.5} />
                  </div>
                  <span style={{ fontSize: '0.95rem', color: '#3a3a3a', fontWeight: 400 }}>{feat}</span>
                </div>
              ))}
            </div>
          </motion.div>
        </div>
      </section>

      {/* ── FOOTER CTA ── */}
      <footer style={{
        padding: '9rem 2rem 6rem',
        background: '#1a1a1a',
        textAlign: 'center',
        position: 'relative', overflow: 'hidden',
      }}>
        {/* Pear watermark bottom left */}
        <div style={{
          position: 'absolute', bottom: '-100px', left: '-80px',
          width: '380px', height: '480px',
          borderRadius: '38% 38% 50% 50% / 28% 28% 50% 50%',
          background: 'rgba(184,146,106,0.07)', pointerEvents: 'none',
        }} />

        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.9 }}
          style={{ maxWidth: '700px', margin: '0 auto', position: 'relative', zIndex: 1 }}
        >
          {/* 🍐 pear icon */}
          <div style={{ fontSize: '3rem', marginBottom: '2.5rem', filter: 'grayscale(0.3)' }}>🍐</div>

          <h2 style={{
            fontFamily: 'var(--eg-font-heading)',
            fontSize: 'clamp(2.5rem, 5vw, 4.5rem)',
            fontWeight: 400, letterSpacing: '-0.03em',
            color: '#fff', marginBottom: '1.5rem', lineHeight: 1.05,
          }}>
            Ready to share<br />
            <span style={{ fontStyle: 'italic', color: '#b8926a' }}>your love story?</span>
          </h2>
          <p style={{ fontSize: '1.1rem', color: 'rgba(255,255,255,0.45)', marginBottom: '4rem', lineHeight: 1.65 }}>
            Join thousands of couples building beautiful wedding sites in minutes.
          </p>

          <button
            onClick={handleSignIn}
            style={{
              display: 'inline-flex', alignItems: 'center', gap: '0.75rem',
              padding: '1.15rem 3.5rem', borderRadius: '100px',
              background: 'linear-gradient(135deg, #b8926a, #8b6b4a)',
              color: '#fff', fontSize: '1.05rem',
              fontWeight: 600, cursor: 'pointer', border: 'none',
              boxShadow: '0 14px 50px rgba(184,146,106,0.45)',
              transition: 'all 0.3s ease',
              fontFamily: 'var(--eg-font-body)',
              letterSpacing: '0.01em',
            }}
            onMouseOver={(e) => { e.currentTarget.style.transform = 'scale(1.04) translateY(-3px)'; }}
            onMouseOut={(e) => { e.currentTarget.style.transform = 'none'; }}
          >
            <Heart size={18} />
            Start Building Free
            <ArrowRight size={16} style={{ opacity: 0.7 }} />
          </button>

          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '2rem', marginTop: '4rem' }}>
            <p style={{ fontSize: '0.75rem', color: 'rgba(255,255,255,0.18)', letterSpacing: '0.08em' }}>
              © 2026 Pearloom
            </p>
            <div style={{ width: '3px', height: '3px', borderRadius: '50%', background: 'rgba(255,255,255,0.15)' }} />
            <p style={{ fontSize: '0.75rem', color: 'rgba(255,255,255,0.18)', letterSpacing: '0.08em' }}>
              Built with love by Pixel Boba Studio
            </p>
            <div style={{ width: '3px', height: '3px', borderRadius: '50%', background: 'rgba(255,255,255,0.15)' }} />
            <p style={{ fontSize: '0.75rem', color: 'rgba(255,255,255,0.18)', letterSpacing: '0.08em' }}>
              Privacy · Terms
            </p>
          </div>
        </motion.div>
      </footer>
    </div>
  );
}
