-- ─────────────────────────────────────────────────────────────
-- Pearloom / supabase/migrations/20260416_event_os.sql
--
-- Event OS — the unified spine that every feature hangs off.
--
-- Design goals:
--   1. An "event" is the root aggregate — a celebration can have
--      multiple events (rehearsal dinner, ceremony, brunch) but
--      one site.
--   2. `pearloom_guests` becomes the single guest identity, keyed
--      by `guest_token` (what the invite email carries). RSVPs,
--      seat assignments, guest photos, guestbook, thank-yous all
--      reference this one row — not three different email strings.
--   3. A `relationship_graph` table makes personalization possible
--      ("friends who carried us here", "guests flying farthest").
--   4. Vendors + vendor_bookings for the two-sided marketplace.
--   5. `guest_personalization` caches per-guest hero copy /
--      microsite overrides generated by the Event Director.
--   6. `post_event_films` tracks the async film rendering job.
--   7. `event_director_sessions` stores the AI agent's plan per event.
--
-- All tables are backwards-compatible — existing site_id-keyed
-- rows continue to work; a nightly job can backfill event rows.
-- ─────────────────────────────────────────────────────────────

-- ── Events ────────────────────────────────────────────────────
-- One celebration (wedding, anniversary, birthday) owns N events.

CREATE TABLE IF NOT EXISTS events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id text NOT NULL,
  owner_email text NOT NULL,
  occasion text NOT NULL,             -- 'wedding' | 'anniversary' | 'birthday' | ...
  name text NOT NULL,                 -- 'The Ceremony', 'Rehearsal Dinner', etc.
  kind text NOT NULL DEFAULT 'main',  -- 'main' | 'rehearsal' | 'brunch' | 'custom'
  start_at timestamptz,
  end_at timestamptz,
  timezone text DEFAULT 'UTC',
  venue_id uuid REFERENCES venues(id) ON DELETE SET NULL,
  is_public boolean DEFAULT true,
  capacity int,
  dress_code text,
  description text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "events: owner access" ON events;
CREATE POLICY "events: owner access"
  ON events
  USING (owner_email = COALESCE(auth.jwt() ->> 'email', ''))
  WITH CHECK (owner_email = COALESCE(auth.jwt() ->> 'email', ''));

CREATE INDEX IF NOT EXISTS idx_events_site_id ON events(site_id);
CREATE INDEX IF NOT EXISTS idx_events_owner_email ON events(owner_email);
CREATE INDEX IF NOT EXISTS idx_events_start_at ON events(start_at);

-- ── Unified Guests ────────────────────────────────────────────
-- Single identity across RSVP, seating, photos, messages.
-- `guest_token` is the slug carried in the invite URL —
-- /i/{guest_token} loads the personalized site, pre-fills RSVP,
-- shows their seat, serves personalized travel tips.

CREATE TABLE IF NOT EXISTS pearloom_guests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id text NOT NULL,
  event_id uuid REFERENCES events(id) ON DELETE CASCADE,
  guest_token text UNIQUE NOT NULL DEFAULT substr(md5(random()::text), 1, 12),
  display_name text NOT NULL,
  pronunciation text,                 -- "KWAH-may" so voice greeter pronounces it right
  pronouns text,
  email text,
  phone text,
  home_city text,
  home_country text,
  relationship_to_host text,          -- 'mother of bride', 'college roommate', etc.
  side text,                          -- 'partner_a' | 'partner_b' | 'both'
  is_plus_one_of uuid REFERENCES pearloom_guests(id) ON DELETE SET NULL,
  language text DEFAULT 'en',
  dietary text[],
  accessibility text[],
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE pearloom_guests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "pearloom_guests: via site owner" ON pearloom_guests;
CREATE POLICY "pearloom_guests: via site owner"
  ON pearloom_guests
  USING (
    EXISTS (
      SELECT 1 FROM sites s
      WHERE s.id = pearloom_guests.site_id
        AND s.creator_email = COALESCE(auth.jwt() ->> 'email', '')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM sites s
      WHERE s.id = pearloom_guests.site_id
        AND s.creator_email = COALESCE(auth.jwt() ->> 'email', '')
    )
  );

CREATE INDEX IF NOT EXISTS idx_pearloom_guests_site ON pearloom_guests(site_id);
CREATE INDEX IF NOT EXISTS idx_pearloom_guests_event ON pearloom_guests(event_id);
CREATE INDEX IF NOT EXISTS idx_pearloom_guests_token ON pearloom_guests(guest_token);
CREATE INDEX IF NOT EXISTS idx_pearloom_guests_email ON pearloom_guests(site_id, email);

-- ── Relationship graph ────────────────────────────────────────
-- Directed edges between guests, or between host and guest.
-- Feeds (a) personalized story copy ("the friend who taught us
-- to surf"), (b) seating optimizer ("cluster college friends"),
-- (c) thank-you generator ("Aunt Linda gave us the blender").

CREATE TABLE IF NOT EXISTS relationship_graph (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id text NOT NULL,
  from_guest_id uuid REFERENCES pearloom_guests(id) ON DELETE CASCADE,
  to_guest_id uuid REFERENCES pearloom_guests(id) ON DELETE CASCADE,
  kind text NOT NULL,                 -- 'friend' | 'family' | 'work' | 'partner' | 'childhood' | 'mentor'
  closeness int CHECK (closeness BETWEEN 1 AND 10),
  story text,                         -- couple-written color about this person
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE relationship_graph ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "relationship_graph: site owner" ON relationship_graph;
CREATE POLICY "relationship_graph: site owner"
  ON relationship_graph
  USING (
    EXISTS (
      SELECT 1 FROM sites s
      WHERE s.id = relationship_graph.site_id
        AND s.creator_email = COALESCE(auth.jwt() ->> 'email', '')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM sites s
      WHERE s.id = relationship_graph.site_id
        AND s.creator_email = COALESCE(auth.jwt() ->> 'email', '')
    )
  );

CREATE INDEX IF NOT EXISTS idx_relationship_graph_site ON relationship_graph(site_id);
CREATE INDEX IF NOT EXISTS idx_relationship_graph_from ON relationship_graph(from_guest_id);
CREATE INDEX IF NOT EXISTS idx_relationship_graph_to ON relationship_graph(to_guest_id);

-- ── Vendors ───────────────────────────────────────────────────
-- Marketplace of photographers, florists, caterers, DJs, etc.
-- We take a cut on each confirmed booking via vendor_bookings.

CREATE TABLE IF NOT EXISTS vendors (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text UNIQUE NOT NULL,
  name text NOT NULL,
  contact_email text NOT NULL,
  phone text,
  website text,
  category text NOT NULL,             -- 'photographer' | 'florist' | 'caterer' | 'dj' | 'venue' | 'planner' | 'officiant'
  city text,
  region text,
  country text DEFAULT 'US',
  price_tier text CHECK (price_tier IN ('$', '$$', '$$$', '$$$$')),
  min_budget_cents bigint,
  max_budget_cents bigint,
  description text,
  portfolio_urls text[],
  rating_avg numeric,
  rating_count int DEFAULT 0,
  stripe_account_id text,             -- Stripe Connect for payouts
  is_verified boolean DEFAULT false,
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE vendors ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "vendors: public read" ON vendors;
CREATE POLICY "vendors: public read"
  ON vendors FOR SELECT USING (is_active = true);

CREATE INDEX IF NOT EXISTS idx_vendors_category ON vendors(category, is_active);
CREATE INDEX IF NOT EXISTS idx_vendors_region ON vendors(city, region);

-- ── Vendor bookings ───────────────────────────────────────────

CREATE TABLE IF NOT EXISTS vendor_bookings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id text NOT NULL,
  event_id uuid REFERENCES events(id) ON DELETE SET NULL,
  vendor_id uuid REFERENCES vendors(id) ON DELETE RESTRICT,
  owner_email text NOT NULL,
  status text NOT NULL DEFAULT 'inquiry',
    -- 'inquiry' | 'proposal_sent' | 'accepted' | 'deposit_paid' | 'paid' | 'completed' | 'cancelled'
  total_cents bigint,
  deposit_cents bigint,
  pearloom_fee_cents bigint,          -- 7-10% platform fee
  proposal_url text,
  contract_url text,
  stripe_payment_intent_id text,
  notes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE vendor_bookings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "vendor_bookings: owner access" ON vendor_bookings;
CREATE POLICY "vendor_bookings: owner access"
  ON vendor_bookings
  USING (owner_email = COALESCE(auth.jwt() ->> 'email', ''))
  WITH CHECK (owner_email = COALESCE(auth.jwt() ->> 'email', ''));

CREATE INDEX IF NOT EXISTS idx_vendor_bookings_site ON vendor_bookings(site_id);
CREATE INDEX IF NOT EXISTS idx_vendor_bookings_vendor ON vendor_bookings(vendor_id);

-- ── Per-guest personalization cache ───────────────────────────
-- Generated lazily on first /i/{token} hit and refreshed when
-- the manifest or guest row changes.

CREATE TABLE IF NOT EXISTS guest_personalization (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id text NOT NULL,
  guest_id uuid UNIQUE REFERENCES pearloom_guests(id) ON DELETE CASCADE,
  hero_copy text,                     -- "Priya — we can't believe it's been 11 years of you picking up the phone at 3am."
  chapter_highlights jsonb,           -- [{chapterId, whyTheyreMentioned}]
  travel_tips jsonb,                  -- {nearestAirport, driveTime, recommendedHotels}
  seat_summary text,                  -- "Table 7 — you're next to your cousin Kian"
  pronunciation_audio_url text,       -- TTS of their name + partner names
  generated_by text DEFAULT 'claude-sonnet-4-6',
  generated_at timestamptz DEFAULT now(),
  expires_at timestamptz
);

ALTER TABLE guest_personalization ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "guest_personalization: site owner" ON guest_personalization;
CREATE POLICY "guest_personalization: site owner"
  ON guest_personalization
  USING (
    EXISTS (
      SELECT 1 FROM sites s
      WHERE s.id = guest_personalization.site_id
        AND s.creator_email = COALESCE(auth.jwt() ->> 'email', '')
    )
  );

CREATE INDEX IF NOT EXISTS idx_guest_personalization_guest ON guest_personalization(guest_id);

-- ── Event Director sessions ───────────────────────────────────
-- Persistent state for the AI planner agent. Each row is one
-- planning conversation with decisions, budget, vendor shortlist.

CREATE TABLE IF NOT EXISTS event_director_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id text NOT NULL,
  event_id uuid REFERENCES events(id) ON DELETE CASCADE,
  owner_email text NOT NULL,
  budget_cents bigint,
  target_date date,
  target_city text,
  guest_count_estimate int,
  constraints jsonb DEFAULT '{}'::jsonb,
  plan jsonb DEFAULT '{}'::jsonb,     -- full plan object the agent maintains
  checklist jsonb DEFAULT '[]'::jsonb,
  vendor_shortlist jsonb DEFAULT '[]'::jsonb,
  conversation jsonb DEFAULT '[]'::jsonb,   -- full agent message history
  status text DEFAULT 'active',       -- 'active' | 'paused' | 'complete'
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE event_director_sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "event_director_sessions: owner access" ON event_director_sessions;
CREATE POLICY "event_director_sessions: owner access"
  ON event_director_sessions
  USING (owner_email = COALESCE(auth.jwt() ->> 'email', ''))
  WITH CHECK (owner_email = COALESCE(auth.jwt() ->> 'email', ''));

CREATE INDEX IF NOT EXISTS idx_director_sessions_site ON event_director_sessions(site_id);

-- ── Post-event film jobs ──────────────────────────────────────

CREATE TABLE IF NOT EXISTS post_event_films (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id text NOT NULL,
  event_id uuid REFERENCES events(id) ON DELETE CASCADE,
  owner_email text NOT NULL,
  status text NOT NULL DEFAULT 'queued',
    -- 'queued' | 'gathering' | 'scripting' | 'rendering' | 'ready' | 'failed'
  script text,                        -- Claude-written narration
  music_track_id text,
  voice_provider text DEFAULT 'elevenlabs',
  output_url text,                    -- R2 URL of final .mp4
  duration_seconds int,
  scheduled_for timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  error text,
  metadata jsonb DEFAULT '{}'::jsonb
);

ALTER TABLE post_event_films ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "post_event_films: owner access" ON post_event_films;
CREATE POLICY "post_event_films: owner access"
  ON post_event_films
  USING (owner_email = COALESCE(auth.jwt() ->> 'email', ''))
  WITH CHECK (owner_email = COALESCE(auth.jwt() ->> 'email', ''));

CREATE INDEX IF NOT EXISTS idx_post_event_films_site ON post_event_films(site_id);
CREATE INDEX IF NOT EXISTS idx_post_event_films_status ON post_event_films(status);

-- ── Day-of live feed (Guest Companion app) ────────────────────
-- Every message the couple sends via the companion app goes
-- here; push notifications fan out from this table.

CREATE TABLE IF NOT EXISTS day_of_announcements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id text NOT NULL,
  event_id uuid REFERENCES events(id) ON DELETE CASCADE,
  author_email text NOT NULL,
  body text NOT NULL,
  kind text DEFAULT 'info',           -- 'info' | 'timeline' | 'location_change' | 'toast_time' | 'alert'
  target_audience text DEFAULT 'all', -- 'all' | 'family' | 'wedding_party' | etc.
  scheduled_for timestamptz,
  sent_at timestamptz,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE day_of_announcements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "day_of_announcements: site owner write" ON day_of_announcements;
CREATE POLICY "day_of_announcements: site owner write"
  ON day_of_announcements
  USING (
    EXISTS (
      SELECT 1 FROM sites s
      WHERE s.id = day_of_announcements.site_id
        AND s.creator_email = COALESCE(auth.jwt() ->> 'email', '')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM sites s
      WHERE s.id = day_of_announcements.site_id
        AND s.creator_email = COALESCE(auth.jwt() ->> 'email', '')
    )
  );

CREATE INDEX IF NOT EXISTS idx_day_of_announcements_site ON day_of_announcements(site_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_day_of_announcements_event ON day_of_announcements(event_id);

-- ── Voice guestbook ───────────────────────────────────────────
-- Audio toasts from guests. Claude transcribes + cleans post-event.

CREATE TABLE IF NOT EXISTS voice_toasts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id text NOT NULL,
  guest_id uuid REFERENCES pearloom_guests(id) ON DELETE SET NULL,
  guest_display_name text,
  audio_url text NOT NULL,
  duration_seconds int,
  transcript text,
  transcript_cleaned text,
  moderation_status text DEFAULT 'pending',
  is_highlight boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE voice_toasts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "voice_toasts: public insert, owner read" ON voice_toasts;
CREATE POLICY "voice_toasts: owner read"
  ON voice_toasts FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM sites s
      WHERE s.id = voice_toasts.site_id
        AND s.creator_email = COALESCE(auth.jwt() ->> 'email', '')
    )
  );

CREATE INDEX IF NOT EXISTS idx_voice_toasts_site ON voice_toasts(site_id, created_at DESC);
